"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from memco.memory.v1 import memory_pb2 as _memory_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MemoryServiceStub:
    """MemoryService is the shared memory surface: the eight operations a client
    uses to find knowledge, contribute to it, and rate what it was given.

    Every identifier crossing this boundary is an external handle a previous
    response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
    id. A handle addresses the memory domain it belongs to, which is why most
    operations take no domain of their own.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> MemoryServiceAsyncStub: ...
    DescribeDomains: _grpc.UnaryUnaryMultiCallable[_memory_pb2.DescribeDomainsRequest, _memory_pb2.DescribeDomainsResponse]
    """DescribeDomains returns the memory domains the caller may name, together
    with the limits the server enforces. It takes no domain itself: it is the
    answer to "which domain?", and the one call a client makes before any other.
    """
    StartSession: _grpc.UnaryUnaryMultiCallable[_memory_pb2.StartSessionRequest, _memory_pb2.StartSessionResponse]
    """StartSession opens a session. Every search made under it is recorded as
    one series, which is what relates the searches an agent runs for a task.
    """
    Search: _grpc.UnaryUnaryMultiCallable[_memory_pb2.SearchRequest, _memory_pb2.SearchResponse]
    """Search retrieves memories for a task-based query, recording the search
    against a session so it can be rated afterwards.
    """
    GetMemory: _grpc.UnaryUnaryMultiCallable[_memory_pb2.GetMemoryRequest, _memory_pb2.GetMemoryResponse]
    """GetMemory returns the memory behind an idx a search delivered, including
    one returned as a reference to an earlier search in the same session.
    """
    CreateMemory: _grpc.UnaryUnaryMultiCallable[_memory_pb2.CreateMemoryRequest, _memory_pb2.CreateMemoryResponse]
    """CreateMemory saves new knowledge. It is accepted asynchronously, so the
    response carries the operation id addressing the write rather than the
    memory it will become.
    """
    EnrichMemory: _grpc.UnaryUnaryMultiCallable[_memory_pb2.EnrichMemoryRequest, _memory_pb2.EnrichMemoryResponse]
    """EnrichMemory adds to a memory a search returned, or opens a new one."""
    ShareFeedback: _grpc.UnaryUnaryMultiCallable[_memory_pb2.ShareFeedbackRequest, _memory_pb2.ShareFeedbackResponse]
    """ShareFeedback rates the results of one search. Ratings are what move the
    reliability signal on an insight.
    """
    RevertMemory: _grpc.UnaryUnaryMultiCallable[_memory_pb2.RevertMemoryRequest, _memory_pb2.RevertMemoryResponse]
    """RevertMemory undoes the caller's own write, addressed by the operation id
    that write returned. Every outcome is a successful call: expired, refused
    and not_found report a caller-visible state, not a service failure.
    """

@_typing.type_check_only
class MemoryServiceAsyncStub(MemoryServiceStub):
    """MemoryService is the shared memory surface: the eight operations a client
    uses to find knowledge, contribute to it, and rate what it was given.

    Every identifier crossing this boundary is an external handle a previous
    response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
    id. A handle addresses the memory domain it belongs to, which is why most
    operations take no domain of their own.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    DescribeDomains: _aio.UnaryUnaryMultiCallable[_memory_pb2.DescribeDomainsRequest, _memory_pb2.DescribeDomainsResponse]  # type: ignore[assignment]
    """DescribeDomains returns the memory domains the caller may name, together
    with the limits the server enforces. It takes no domain itself: it is the
    answer to "which domain?", and the one call a client makes before any other.
    """
    StartSession: _aio.UnaryUnaryMultiCallable[_memory_pb2.StartSessionRequest, _memory_pb2.StartSessionResponse]  # type: ignore[assignment]
    """StartSession opens a session. Every search made under it is recorded as
    one series, which is what relates the searches an agent runs for a task.
    """
    Search: _aio.UnaryUnaryMultiCallable[_memory_pb2.SearchRequest, _memory_pb2.SearchResponse]  # type: ignore[assignment]
    """Search retrieves memories for a task-based query, recording the search
    against a session so it can be rated afterwards.
    """
    GetMemory: _aio.UnaryUnaryMultiCallable[_memory_pb2.GetMemoryRequest, _memory_pb2.GetMemoryResponse]  # type: ignore[assignment]
    """GetMemory returns the memory behind an idx a search delivered, including
    one returned as a reference to an earlier search in the same session.
    """
    CreateMemory: _aio.UnaryUnaryMultiCallable[_memory_pb2.CreateMemoryRequest, _memory_pb2.CreateMemoryResponse]  # type: ignore[assignment]
    """CreateMemory saves new knowledge. It is accepted asynchronously, so the
    response carries the operation id addressing the write rather than the
    memory it will become.
    """
    EnrichMemory: _aio.UnaryUnaryMultiCallable[_memory_pb2.EnrichMemoryRequest, _memory_pb2.EnrichMemoryResponse]  # type: ignore[assignment]
    """EnrichMemory adds to a memory a search returned, or opens a new one."""
    ShareFeedback: _aio.UnaryUnaryMultiCallable[_memory_pb2.ShareFeedbackRequest, _memory_pb2.ShareFeedbackResponse]  # type: ignore[assignment]
    """ShareFeedback rates the results of one search. Ratings are what move the
    reliability signal on an insight.
    """
    RevertMemory: _aio.UnaryUnaryMultiCallable[_memory_pb2.RevertMemoryRequest, _memory_pb2.RevertMemoryResponse]  # type: ignore[assignment]
    """RevertMemory undoes the caller's own write, addressed by the operation id
    that write returned. Every outcome is a successful call: expired, refused
    and not_found report a caller-visible state, not a service failure.
    """

class MemoryServiceServicer(metaclass=_abc_1.ABCMeta):
    """MemoryService is the shared memory surface: the eight operations a client
    uses to find knowledge, contribute to it, and rate what it was given.

    Every identifier crossing this boundary is an external handle a previous
    response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
    id. A handle addresses the memory domain it belongs to, which is why most
    operations take no domain of their own.
    """

    @_abc_1.abstractmethod
    def DescribeDomains(
        self,
        request: _memory_pb2.DescribeDomainsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.DescribeDomainsResponse, _abc.Awaitable[_memory_pb2.DescribeDomainsResponse]]:
        """DescribeDomains returns the memory domains the caller may name, together
        with the limits the server enforces. It takes no domain itself: it is the
        answer to "which domain?", and the one call a client makes before any other.
        """

    @_abc_1.abstractmethod
    def StartSession(
        self,
        request: _memory_pb2.StartSessionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.StartSessionResponse, _abc.Awaitable[_memory_pb2.StartSessionResponse]]:
        """StartSession opens a session. Every search made under it is recorded as
        one series, which is what relates the searches an agent runs for a task.
        """

    @_abc_1.abstractmethod
    def Search(
        self,
        request: _memory_pb2.SearchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.SearchResponse, _abc.Awaitable[_memory_pb2.SearchResponse]]:
        """Search retrieves memories for a task-based query, recording the search
        against a session so it can be rated afterwards.
        """

    @_abc_1.abstractmethod
    def GetMemory(
        self,
        request: _memory_pb2.GetMemoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.GetMemoryResponse, _abc.Awaitable[_memory_pb2.GetMemoryResponse]]:
        """GetMemory returns the memory behind an idx a search delivered, including
        one returned as a reference to an earlier search in the same session.
        """

    @_abc_1.abstractmethod
    def CreateMemory(
        self,
        request: _memory_pb2.CreateMemoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.CreateMemoryResponse, _abc.Awaitable[_memory_pb2.CreateMemoryResponse]]:
        """CreateMemory saves new knowledge. It is accepted asynchronously, so the
        response carries the operation id addressing the write rather than the
        memory it will become.
        """

    @_abc_1.abstractmethod
    def EnrichMemory(
        self,
        request: _memory_pb2.EnrichMemoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.EnrichMemoryResponse, _abc.Awaitable[_memory_pb2.EnrichMemoryResponse]]:
        """EnrichMemory adds to a memory a search returned, or opens a new one."""

    @_abc_1.abstractmethod
    def ShareFeedback(
        self,
        request: _memory_pb2.ShareFeedbackRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.ShareFeedbackResponse, _abc.Awaitable[_memory_pb2.ShareFeedbackResponse]]:
        """ShareFeedback rates the results of one search. Ratings are what move the
        reliability signal on an insight.
        """

    @_abc_1.abstractmethod
    def RevertMemory(
        self,
        request: _memory_pb2.RevertMemoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_memory_pb2.RevertMemoryResponse, _abc.Awaitable[_memory_pb2.RevertMemoryResponse]]:
        """RevertMemory undoes the caller's own write, addressed by the operation id
        that write returned. Every outcome is a successful call: expired, refused
        and not_found report a caller-visible state, not a service failure.
        """

def add_MemoryServiceServicer_to_server(servicer: MemoryServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
