# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memco.memory.v1 import memory_pb2 as memco_dot_memory_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memco/memory/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """MemoryService is the shared memory surface: the eight operations a client
    uses to find knowledge, contribute to it, and rate what it was given.

    Every identifier crossing this boundary is an external handle a previous
    response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
    id. A handle addresses the memory domain it belongs to, which is why most
    operations take no domain of their own.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeDomains = channel.unary_unary(
                '/memco.memory.v1.MemoryService/DescribeDomains',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.DescribeDomainsRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.DescribeDomainsResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/memco.memory.v1.MemoryService/StartSession',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/memco.memory.v1.MemoryService/Search',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/memco.memory.v1.MemoryService/GetMemory',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.CreateMemory = channel.unary_unary(
                '/memco.memory.v1.MemoryService/CreateMemory',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.CreateMemoryRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.CreateMemoryResponse.FromString,
                _registered_method=True)
        self.EnrichMemory = channel.unary_unary(
                '/memco.memory.v1.MemoryService/EnrichMemory',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.EnrichMemoryRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.EnrichMemoryResponse.FromString,
                _registered_method=True)
        self.ShareFeedback = channel.unary_unary(
                '/memco.memory.v1.MemoryService/ShareFeedback',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.ShareFeedbackRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.ShareFeedbackResponse.FromString,
                _registered_method=True)
        self.RevertMemory = channel.unary_unary(
                '/memco.memory.v1.MemoryService/RevertMemory',
                request_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.RevertMemoryRequest.SerializeToString,
                response_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.RevertMemoryResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """MemoryService is the shared memory surface: the eight operations a client
    uses to find knowledge, contribute to it, and rate what it was given.

    Every identifier crossing this boundary is an external handle a previous
    response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
    id. A handle addresses the memory domain it belongs to, which is why most
    operations take no domain of their own.
    """

    def DescribeDomains(self, request, context):
        """DescribeDomains returns the memory domains the caller may name, together
        with the limits the server enforces. It takes no domain itself: it is the
        answer to "which domain?", and the one call a client makes before any other.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """StartSession opens a session. Every search made under it is recorded as
        one series, which is what relates the searches an agent runs for a task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search retrieves memories for a task-based query, recording the search
        against a session so it can be rated afterwards.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """GetMemory returns the memory behind an idx a search delivered, including
        one returned as a reference to an earlier search in the same session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMemory(self, request, context):
        """CreateMemory saves new knowledge. It is accepted asynchronously, so the
        response carries the operation id addressing the write rather than the
        memory it will become.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichMemory(self, request, context):
        """EnrichMemory adds to a memory a search returned, or opens a new one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareFeedback(self, request, context):
        """ShareFeedback rates the results of one search. Ratings are what move the
        reliability signal on an insight.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevertMemory(self, request, context):
        """RevertMemory undoes the caller's own write, addressed by the operation id
        that write returned. Every outcome is a successful call: expired, refused
        and not_found report a caller-visible state, not a service failure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeDomains': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeDomains,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.DescribeDomainsRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.DescribeDomainsResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.StartSessionRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.StartSessionResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.SearchRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.SearchResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.GetMemoryRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.GetMemoryResponse.SerializeToString,
            ),
            'CreateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMemory,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.CreateMemoryRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.CreateMemoryResponse.SerializeToString,
            ),
            'EnrichMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichMemory,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.EnrichMemoryRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.EnrichMemoryResponse.SerializeToString,
            ),
            'ShareFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareFeedback,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.ShareFeedbackRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.ShareFeedbackResponse.SerializeToString,
            ),
            'RevertMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.RevertMemory,
                    request_deserializer=memco_dot_memory_dot_v1_dot_memory__pb2.RevertMemoryRequest.FromString,
                    response_serializer=memco_dot_memory_dot_v1_dot_memory__pb2.RevertMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memco.memory.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memco.memory.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """MemoryService is the shared memory surface: the eight operations a client
    uses to find knowledge, contribute to it, and rate what it was given.

    Every identifier crossing this boundary is an external handle a previous
    response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
    id. A handle addresses the memory domain it belongs to, which is why most
    operations take no domain of their own.
    """

    @staticmethod
    def DescribeDomains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/DescribeDomains',
            memco_dot_memory_dot_v1_dot_memory__pb2.DescribeDomainsRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.DescribeDomainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/StartSession',
            memco_dot_memory_dot_v1_dot_memory__pb2.StartSessionRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/Search',
            memco_dot_memory_dot_v1_dot_memory__pb2.SearchRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/GetMemory',
            memco_dot_memory_dot_v1_dot_memory__pb2.GetMemoryRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/CreateMemory',
            memco_dot_memory_dot_v1_dot_memory__pb2.CreateMemoryRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.CreateMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/EnrichMemory',
            memco_dot_memory_dot_v1_dot_memory__pb2.EnrichMemoryRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.EnrichMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/ShareFeedback',
            memco_dot_memory_dot_v1_dot_memory__pb2.ShareFeedbackRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.ShareFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevertMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memco.memory.v1.MemoryService/RevertMemory',
            memco_dot_memory_dot_v1_dot_memory__pb2.RevertMemoryRequest.SerializeToString,
            memco_dot_memory_dot_v1_dot_memory__pb2.RevertMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
