// Code generated by scripts/sync_tool_docs.py. DO NOT EDIT.

package memory

// The service's agent-facing tool copy, generated from the tool manifest with
// every ${tool:...} marker resolved: an offered operation is spelled as a model
// calls it (memco_search), one a bound session answers keeps its bare name.
// Left behind: rpc, annotations, title and the manifest's instructions. Every
// literal is positional and every copy a raw string, so gofmt has nothing to
// realign.

// ToolPrefix is prepended to each offered operation's name.
const ToolPrefix = "memco_"

// OfferedTools are the operations offered to a model, in the order a task uses them.
var OfferedTools = []string{"search", "get_memory", "create_memory", "enrich_memory", "share_feedback", "revert_memory"}

// AnsweredTools are named by the copy but already answered by a bound session.
var AnsweredTools = []string{"list_domains", "start_session"}

// ToolCopies holds every tool the manifest publishes, in its order.
var ToolCopies = []ToolCopy{
	{
		"create_memory",
		`Save new knowledge to Memco Shared Memory, where your teammates and their agents will find it.
Call when: you have learned something non-obvious that would help your team — why something turned out the way it did, how something actually behaves, something that was hard to establish, or a decision and its rationale — or your user has corrected you. Search first: when a related memory already exists, memco_enrich_memory extends it instead of leaving a near-duplicate beside it.
Pass either a domain or a session_id — a call naming neither is refused. Naming the session you have been searching in saves the memory into that session's domain and records it as part of that work; naming a domain alone saves a standalone memory.
Each memory needs a query (what someone would search to find this), a title, and content describing what you learned. list_domains says what belongs in the chosen domain and which tags to use.`,
		[]ParameterCopy{
			{"content", `(Required) The knowledge to save. Should be a concise, non-trivial finding that others can learn from. Supports markdown formatting. Title and content together must be at most 5000 characters; split a longer finding across several memories.`},
			{"domain", `The memory domain to save into. Required unless you pass session_id, which supplies the domain of the session it names. Call list_domains for the domains available to you.`},
			{"query", `(Required) A query describing what someone would search to find this memory, such as a question or problem statement. Use markdown formatting for readability. At most 1000 characters.`},
			{"session_id", `The session this memory was learned during, as returned by start_session or a previous search. It records the memory as part of that series of work, and supplies the memory domain, so the domain argument is not needed and is ignored. Omit it to save a standalone memory.`},
			{"source", `The source of the content: user for human-corrected information, or agent for self-discovered insights without human correction. Unset is read as agent.`},
			{"tags", `Tags describing the subject and context, narrowing what this applies to. Call list_domains for the tag types this domain uses. Supply as many as you can determine for the best results.`},
			{"title", `(Required) A short title describing what this memory is about. Title and content together must be at most 5000 characters.`},
		},
	},
	{
		"enrich_memory",
		`Add information to an existing memory in Memco Shared Memory, so your finding lands beside the one it belongs to rather than in a memory that competes with it.
Call when: a search returned a memory close to what you learned but incomplete, out of date, or missing the approach you took. Use memco_create_memory instead when nothing returned covers the subject at all.
Set memory_idx to the memory you want to extend (from search results), or 'new' to add a standalone addition. Keep an addition concise and say only what is not already there. The addition lands in the domain the search session ran in; you do not name one.`,
		[]ParameterCopy{
			{"content", `(Required) The knowledge you want to add. Use markdown formatting for readability. Title and content together must be at most 5000 characters; split a longer finding across several enrichments.`},
			{"memory_idx", `(Required) The memory_idx of the memory you are enriching. If you are adding to a new memory, set memory_idx to 'new'.`},
			{"session_id", `(Required) The session id you are enriching a memory in. The ID was included in the response from memco_search.`},
			{"source", `The source of the content: user for human-corrected information, or agent for self-discovered insights without human correction. Unset is read as agent.`},
			{"sources", `A list of memories received from Memco Shared Memory that proved helpful in reaching this insight. Up to 20 sources can be included.`},
			{"tags", `Tags describing the subject and context, narrowing what this applies to. Call list_domains for the tag types this domain uses. Supply as many as you can determine for the best results.`},
			{"title", `(Required) A short title describing what you learned. Title and content together must be at most 5000 characters.`},
		},
	},
	{
		"get_memory",
		`Fetch one memory a search returned, by its idx, and get it back in full.
Call when: you hold an idx whose content is not in front of you — a search returned the memory as a reference to an idx that carried it earlier, or another agent did the searching and passed you the handle. An insight's idx returns the memory holding it.
The idx is all it takes: copy it exactly as it appeared in a search response — it cannot be constructed by hand — and nothing else is needed to name the result.
When a result carries a reference instead of content, ask by the value in its own idx, never the value in its reference. A result with idx "memory-THIS-1" and reference "memory-EARLIER-1" is fetched with "memory-THIS-1": the reference says where the content was delivered, not what to ask for. Both return the same text, but only its own idx keeps a later rating with the search you are working in.`,
		[]ParameterCopy{
			{"idx", `(Required) The idx of the result to fetch, copied exactly as it appeared in a search response. An insight's idx returns the memory holding it.`},
		},
	},
	{
		"import_memories",
		`Fill a new or nearly empty workspace with the knowledge a team already holds, in one call, so memory starts out useful instead of empty.
Call when: filling a workspace that has little or nothing in it, or onboarding someone into one — a teammate joining, or your own first connection to it. This is a setup step, done once: you are handing over what is already known, not recording something you just learned. Use memco_create_memory for a single finding from this session.
Pass either a domain or a session_id — a call naming neither is refused. Each memory needs at least one query describing what someone would search to find it, and at least one insight with a title and content. At most 25 memories per call, 20 queries and 10 insights each; send several calls for more.
Every memory is checked on the way in and starts at your own standing, exactly as a single write does. The response answers per memory, by the position you sent it in: one that was refused says why, and one whose content is already held says so and is not written again.`,
		[]ParameterCopy{
			{"domain", `The memory domain to import into. Required unless you pass session_id, which supplies the domain of the session it names. Call list_domains for the domains available to you.`},
			{"memories", `(Required) The memories to contribute. At least one, at most 25 per call; send several calls for more.`},
			{"session_id", `The session these memories were contributed during, as returned by start_session or a previous search. It records them as part of that series of work, and supplies the memory domain, so the domain argument is not needed and is ignored.`},
		},
	},
	{
		"list_domains",
		`List the memory domains available to you and describe each one: what it holds, when to search it, what belongs in it and what does not, and the tag vocabulary and format it uses.
Call when: before your first search or write of a task, and whenever you are unsure which domain a question or a finding belongs to. The slug you choose is what start_session, memco_search and memco_create_memory take as their domain argument.`,
		nil,
	},
	{
		"revert_memory",
		`Undo a memory you just wrote, using the operation id that memco_create_memory or memco_enrich_memory returned.
Call when: you saved something by mistake — wrong content, the wrong domain, or something that should not have been shared.
Your entry is always removed. The memory it belongs to is removed with it only when your entry was the last one in it — so reverting a memco_create_memory, or an memco_enrich_memory you sent with memory_idx 'new', removes that memory too, while reverting an addition to a memory that holds other entries leaves the memory in place. You can only revert your own writes, and only within 2 days.`,
		[]ParameterCopy{
			{"operation_id", `(Required) The operation id returned by the memco_create_memory or memco_enrich_memory call you want to undo, for example 'create-hpc08-1'.`},
		},
	},
	{
		"search",
		`Search Memco Shared Memory for existing knowledge before working a problem out from scratch. It holds what your teammates and their agents have already established and recorded.
Call when: you start a task, plan a non-trivial piece of work, meet something unfamiliar, hit a question you cannot answer from what you already know, or are about to reason out something a teammate may already have settled. Search first, then work.
Pass either a domain or a session_id — a search naming neither is refused. Naming a session runs the search in that session's domain and records it alongside the other searches made for the same task; naming a domain alone starts a session for this one search.
The query uses both keyword and semantic search, and is intended for a single concept per query. If you need varied information, make multiple queries.
Supply tags to narrow the results; list_domains lists the tag types the chosen domain uses and the format they take.
Results come back most-relevant-first and are bounded, so a search returns what fits rather than everything that matched; the response says what it left out. Memories are written by your teammates and their agents. Within one session a result already returned is not repeated — it comes back as a reference to the idx that carried it, which memco_get_memory turns back into content.`,
		[]ParameterCopy{
			{"domain", `The memory domain to search in. Required unless you pass session_id, which supplies the domain of the session it names. Call list_domains for the domains available to you.`},
			{"query", `(Required) A task-based query from the user such as a question, statement, or task description. To ensure readability, use markdown formatting. At most 1000 characters.`},
			{"session_id", `The session to record this search under, as returned by start_session or a previous search. The search runs in that session's memory domain, so the domain argument is not needed and is ignored. Omit this to start a new session, in which case a domain is required.`},
			{"tags", `Tags describing the subject and context, narrowing what this applies to. Call list_domains for the tag types this domain uses. Supply as many as you can determine for the best results.`},
		},
	},
	{
		"share_feedback",
		`Rate the relevance and correctness of search results. Only you can tell whether a result answered the query, and these ratings shape which results are shown next.
Call when: you have read the results of a search and can judge them — once per search, while its session id is still to hand.
The feedback is recorded against the domain the search session ran in; you do not name one.`,
		[]ParameterCopy{
			{"feedback", `(Required) A list of ratings, one per result you want to rate. Up to 10 ratings can be included in each call.`},
			{"session_id", `(Required) The session you are providing feedback for. The ID was included in the response from memco_search.`},
		},
	},
	{
		"start_session",
		`Start a session and get its id. A session groups the searches you make while working on one task, so they are recorded as the series they are rather than as unrelated one-offs.
Call when: at the start of work that will involve multiple related searches, or when you want a stable session id to reuse across memco_search, memco_share_feedback, and memco_enrich_memory. Pass the id as session_id to every search you make for it — and to memco_share_feedback and memco_enrich_memory. A session stays usable for as long as you keep naming it.`,
		[]ParameterCopy{
			{"domain", `(Required) The memory domain to operate in. Call list_domains for the domains available to you.`},
		},
	},
}

// NestedCopy holds import_memories' nested request fields, by manifest path.
var NestedCopy = []ParameterCopy{
	{"memories[].insights", `(Required) The findings this memory holds. At least one, at most 10.`},
	{"memories[].insights[].content", `(Required) The knowledge to save. Should be a concise, non-trivial finding that others can learn from. Supports markdown formatting.`},
	{"memories[].insights[].title", `(Required) A short title describing what this insight is about. Title and content together must be at most 5000 characters.`},
	{"memories[].queries", `(Required) The queries someone would search to find this memory, such as questions or problem statements. At least one, at most 20.`},
	{"memories[].tags", `Tags describing the subject and context, narrowing what this memory applies to. Call list_domains for the tag types this domain uses.`},
}

// EntryCopies holds the fields of the entries a list argument takes, once per
// type an entry is.
var EntryCopies = []EntryCopy{
	{
		"Tag",
		[]ParameterCopy{
			{"type", `(Required) The tag's type, one of the tag types this domain uses.`},
			{"value", `(Required) The tag's value within its type.`},
			{"version", `The version of what the tag names. Set it only on a tag type that takes a version, as list_domains states.`},
		},
	},
	{
		"FeedbackRating",
		[]ParameterCopy{
			{"comment", `An optional comment on the result, at most 5000 characters.`},
			{"correct", `Set to true if the result's content was accurate.`},
			{"idx", `(Required) The idx of the result to rate, copied exactly as it appears in the search response; it cannot be constructed by hand. Use an insight's idx for a specific insight, or a memory's own idx to apply the rating to every insight under it.`},
			{"relevant", `Set to true if the result was a good match for the query.`},
		},
	},
}
