"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from memcoai.admin.v1 import admin_pb2 as _admin_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AdminServiceStub:
    """AdminService is the organization-administration surface: the memory networks
    an organization places its people in, the identity-provider groups that place
    them in an enterprise organization, and the external users an organization
    drives through API keys.

    It is reached with a token from TokenService, and every call is bounded by the
    scope that token carries. The organization is always the credential's own — no
    request names one — so a token can never address another tenant.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AdminServiceAsyncStub: ...
    ListNetworks: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ListNetworksRequest, _admin_pb2.ListNetworksResponse]
    """ListNetworks returns one page of the organization's memory networks."""
    CreateNetwork: _grpc.UnaryUnaryMultiCallable[_admin_pb2.CreateNetworkRequest, _admin_pb2.Network]
    """CreateNetwork adds a memory network. A child takes its parent's domain."""
    UpdateNetwork: _grpc.UnaryUnaryMultiCallable[_admin_pb2.UpdateNetworkRequest, _admin_pb2.Network]
    """UpdateNetwork changes a network's name, parent, scope, owner or description."""
    DeleteNetwork: _grpc.UnaryUnaryMultiCallable[_admin_pb2.DeleteNetworkRequest, _admin_pb2.DeleteNetworkResponse]
    """DeleteNetwork removes a network and everything that hangs off it, reporting
    what the cascade took with it.
    """
    ListNetworkMembers: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ListNetworkMembersRequest, _admin_pb2.ListNetworkMembersResponse]
    """ListNetworkMembers returns the users assigned to a network."""
    AddNetworkMember: _grpc.UnaryUnaryMultiCallable[_admin_pb2.AddNetworkMemberRequest, _admin_pb2.AddNetworkMemberResponse]
    """AddNetworkMember assigns a user to a network. A user already placed in
    another network of the same domain is refused unless force is set, which
    relocates them.
    """
    RemoveNetworkMember: _grpc.UnaryUnaryMultiCallable[_admin_pb2.RemoveNetworkMemberRequest, _admin_pb2.RemoveNetworkMemberResponse]
    """RemoveNetworkMember unassigns a user from a network."""
    ListGroups: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ListGroupsRequest, _admin_pb2.ListGroupsResponse]
    """ListGroups returns one page of the organization's identity-provider groups.
    Available to enterprise organizations only.
    """
    ListGroupMembers: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ListGroupMembersRequest, _admin_pb2.ListGroupMembersResponse]
    """ListGroupMembers returns the users in an identity-provider group. Available
    to enterprise organizations only.
    """
    AddNetworkGroup: _grpc.UnaryUnaryMultiCallable[_admin_pb2.AddNetworkGroupRequest, _admin_pb2.AddNetworkGroupResponse]
    """AddNetworkGroup assigns an identity-provider group to a network, which is how
    an enterprise organization places people in networks. A group holds one
    network per memory domain, so this replaces the group's network in the
    network's domain. Available to enterprise organizations only.
    """
    RemoveNetworkGroup: _grpc.UnaryUnaryMultiCallable[_admin_pb2.RemoveNetworkGroupRequest, _admin_pb2.RemoveNetworkGroupResponse]
    """RemoveNetworkGroup takes an identity-provider group out of a network. Its
    networks in other memory domains are unaffected. Available to enterprise
    organizations only.
    """
    ListExternalUsers: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ListExternalUsersRequest, _admin_pb2.ListExternalUsersResponse]
    """ListExternalUsers returns one page of the organization's external users."""
    GetExternalUser: _grpc.UnaryUnaryMultiCallable[_admin_pb2.GetExternalUserRequest, _admin_pb2.ExternalUser]
    """GetExternalUser returns the external user with the external id."""
    CreateExternalUser: _grpc.UnaryUnaryMultiCallable[_admin_pb2.CreateExternalUserRequest, _admin_pb2.ExternalUser]
    """CreateExternalUser adds an external user: a principal with no sign-in of its
    own, driven through API keys, holding reader, creator or auditor and never
    admin. It starts in no network; AddNetworkMember places it in a
    customer-scoped one.
    """
    UpdateExternalUser: _grpc.UnaryUnaryMultiCallable[_admin_pb2.UpdateExternalUserRequest, _admin_pb2.ExternalUser]
    """UpdateExternalUser changes an external user's name, email or roles. The
    external id is immutable.
    """
    DeleteExternalUser: _grpc.UnaryUnaryMultiCallable[_admin_pb2.DeleteExternalUserRequest, _admin_pb2.DeleteExternalUserResponse]
    """DeleteExternalUser removes an external user and every key it holds."""
    ListExternalUserKeys: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ListExternalUserKeysRequest, _admin_pb2.ListExternalUserKeysResponse]
    """ListExternalUserKeys returns an external user's API keys, without their values."""
    CreateExternalUserKey: _grpc.UnaryUnaryMultiCallable[_admin_pb2.CreateExternalUserKeyRequest, _admin_pb2.CreateExternalUserKeyResponse]
    """CreateExternalUserKey mints an API key for an external user from a preset its
    roles allow, expiring within three months. The key is returned once.
    """
    DeleteExternalUserKey: _grpc.UnaryUnaryMultiCallable[_admin_pb2.DeleteExternalUserKeyRequest, _admin_pb2.DeleteExternalUserKeyResponse]
    """DeleteExternalUserKey revokes one of an external user's API keys."""
    ImpersonateExternalUser: _grpc.UnaryUnaryMultiCallable[_admin_pb2.ImpersonateExternalUserRequest, _admin_pb2.ImpersonationKey]
    """ImpersonateExternalUser mints a short-lived key that acts as the external
    user, carrying its content role and, for an auditor, the audit stream. Only an
    API client holding the admin grant may call it.
    """
    EndImpersonation: _grpc.UnaryUnaryMultiCallable[_admin_pb2.EndImpersonationRequest, _admin_pb2.EndImpersonationResponse]
    """EndImpersonation revokes an impersonation key before it expires."""

@_typing.type_check_only
class AdminServiceAsyncStub(AdminServiceStub):
    """AdminService is the organization-administration surface: the memory networks
    an organization places its people in, the identity-provider groups that place
    them in an enterprise organization, and the external users an organization
    drives through API keys.

    It is reached with a token from TokenService, and every call is bounded by the
    scope that token carries. The organization is always the credential's own — no
    request names one — so a token can never address another tenant.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ListNetworks: _aio.UnaryUnaryMultiCallable[_admin_pb2.ListNetworksRequest, _admin_pb2.ListNetworksResponse]  # type: ignore[assignment]
    """ListNetworks returns one page of the organization's memory networks."""
    CreateNetwork: _aio.UnaryUnaryMultiCallable[_admin_pb2.CreateNetworkRequest, _admin_pb2.Network]  # type: ignore[assignment]
    """CreateNetwork adds a memory network. A child takes its parent's domain."""
    UpdateNetwork: _aio.UnaryUnaryMultiCallable[_admin_pb2.UpdateNetworkRequest, _admin_pb2.Network]  # type: ignore[assignment]
    """UpdateNetwork changes a network's name, parent, scope, owner or description."""
    DeleteNetwork: _aio.UnaryUnaryMultiCallable[_admin_pb2.DeleteNetworkRequest, _admin_pb2.DeleteNetworkResponse]  # type: ignore[assignment]
    """DeleteNetwork removes a network and everything that hangs off it, reporting
    what the cascade took with it.
    """
    ListNetworkMembers: _aio.UnaryUnaryMultiCallable[_admin_pb2.ListNetworkMembersRequest, _admin_pb2.ListNetworkMembersResponse]  # type: ignore[assignment]
    """ListNetworkMembers returns the users assigned to a network."""
    AddNetworkMember: _aio.UnaryUnaryMultiCallable[_admin_pb2.AddNetworkMemberRequest, _admin_pb2.AddNetworkMemberResponse]  # type: ignore[assignment]
    """AddNetworkMember assigns a user to a network. A user already placed in
    another network of the same domain is refused unless force is set, which
    relocates them.
    """
    RemoveNetworkMember: _aio.UnaryUnaryMultiCallable[_admin_pb2.RemoveNetworkMemberRequest, _admin_pb2.RemoveNetworkMemberResponse]  # type: ignore[assignment]
    """RemoveNetworkMember unassigns a user from a network."""
    ListGroups: _aio.UnaryUnaryMultiCallable[_admin_pb2.ListGroupsRequest, _admin_pb2.ListGroupsResponse]  # type: ignore[assignment]
    """ListGroups returns one page of the organization's identity-provider groups.
    Available to enterprise organizations only.
    """
    ListGroupMembers: _aio.UnaryUnaryMultiCallable[_admin_pb2.ListGroupMembersRequest, _admin_pb2.ListGroupMembersResponse]  # type: ignore[assignment]
    """ListGroupMembers returns the users in an identity-provider group. Available
    to enterprise organizations only.
    """
    AddNetworkGroup: _aio.UnaryUnaryMultiCallable[_admin_pb2.AddNetworkGroupRequest, _admin_pb2.AddNetworkGroupResponse]  # type: ignore[assignment]
    """AddNetworkGroup assigns an identity-provider group to a network, which is how
    an enterprise organization places people in networks. A group holds one
    network per memory domain, so this replaces the group's network in the
    network's domain. Available to enterprise organizations only.
    """
    RemoveNetworkGroup: _aio.UnaryUnaryMultiCallable[_admin_pb2.RemoveNetworkGroupRequest, _admin_pb2.RemoveNetworkGroupResponse]  # type: ignore[assignment]
    """RemoveNetworkGroup takes an identity-provider group out of a network. Its
    networks in other memory domains are unaffected. Available to enterprise
    organizations only.
    """
    ListExternalUsers: _aio.UnaryUnaryMultiCallable[_admin_pb2.ListExternalUsersRequest, _admin_pb2.ListExternalUsersResponse]  # type: ignore[assignment]
    """ListExternalUsers returns one page of the organization's external users."""
    GetExternalUser: _aio.UnaryUnaryMultiCallable[_admin_pb2.GetExternalUserRequest, _admin_pb2.ExternalUser]  # type: ignore[assignment]
    """GetExternalUser returns the external user with the external id."""
    CreateExternalUser: _aio.UnaryUnaryMultiCallable[_admin_pb2.CreateExternalUserRequest, _admin_pb2.ExternalUser]  # type: ignore[assignment]
    """CreateExternalUser adds an external user: a principal with no sign-in of its
    own, driven through API keys, holding reader, creator or auditor and never
    admin. It starts in no network; AddNetworkMember places it in a
    customer-scoped one.
    """
    UpdateExternalUser: _aio.UnaryUnaryMultiCallable[_admin_pb2.UpdateExternalUserRequest, _admin_pb2.ExternalUser]  # type: ignore[assignment]
    """UpdateExternalUser changes an external user's name, email or roles. The
    external id is immutable.
    """
    DeleteExternalUser: _aio.UnaryUnaryMultiCallable[_admin_pb2.DeleteExternalUserRequest, _admin_pb2.DeleteExternalUserResponse]  # type: ignore[assignment]
    """DeleteExternalUser removes an external user and every key it holds."""
    ListExternalUserKeys: _aio.UnaryUnaryMultiCallable[_admin_pb2.ListExternalUserKeysRequest, _admin_pb2.ListExternalUserKeysResponse]  # type: ignore[assignment]
    """ListExternalUserKeys returns an external user's API keys, without their values."""
    CreateExternalUserKey: _aio.UnaryUnaryMultiCallable[_admin_pb2.CreateExternalUserKeyRequest, _admin_pb2.CreateExternalUserKeyResponse]  # type: ignore[assignment]
    """CreateExternalUserKey mints an API key for an external user from a preset its
    roles allow, expiring within three months. The key is returned once.
    """
    DeleteExternalUserKey: _aio.UnaryUnaryMultiCallable[_admin_pb2.DeleteExternalUserKeyRequest, _admin_pb2.DeleteExternalUserKeyResponse]  # type: ignore[assignment]
    """DeleteExternalUserKey revokes one of an external user's API keys."""
    ImpersonateExternalUser: _aio.UnaryUnaryMultiCallable[_admin_pb2.ImpersonateExternalUserRequest, _admin_pb2.ImpersonationKey]  # type: ignore[assignment]
    """ImpersonateExternalUser mints a short-lived key that acts as the external
    user, carrying its content role and, for an auditor, the audit stream. Only an
    API client holding the admin grant may call it.
    """
    EndImpersonation: _aio.UnaryUnaryMultiCallable[_admin_pb2.EndImpersonationRequest, _admin_pb2.EndImpersonationResponse]  # type: ignore[assignment]
    """EndImpersonation revokes an impersonation key before it expires."""

class AdminServiceServicer(metaclass=_abc_1.ABCMeta):
    """AdminService is the organization-administration surface: the memory networks
    an organization places its people in, the identity-provider groups that place
    them in an enterprise organization, and the external users an organization
    drives through API keys.

    It is reached with a token from TokenService, and every call is bounded by the
    scope that token carries. The organization is always the credential's own — no
    request names one — so a token can never address another tenant.
    """

    @_abc_1.abstractmethod
    def ListNetworks(
        self,
        request: _admin_pb2.ListNetworksRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ListNetworksResponse, _abc.Awaitable[_admin_pb2.ListNetworksResponse]]:
        """ListNetworks returns one page of the organization's memory networks."""

    @_abc_1.abstractmethod
    def CreateNetwork(
        self,
        request: _admin_pb2.CreateNetworkRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.Network, _abc.Awaitable[_admin_pb2.Network]]:
        """CreateNetwork adds a memory network. A child takes its parent's domain."""

    @_abc_1.abstractmethod
    def UpdateNetwork(
        self,
        request: _admin_pb2.UpdateNetworkRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.Network, _abc.Awaitable[_admin_pb2.Network]]:
        """UpdateNetwork changes a network's name, parent, scope, owner or description."""

    @_abc_1.abstractmethod
    def DeleteNetwork(
        self,
        request: _admin_pb2.DeleteNetworkRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.DeleteNetworkResponse, _abc.Awaitable[_admin_pb2.DeleteNetworkResponse]]:
        """DeleteNetwork removes a network and everything that hangs off it, reporting
        what the cascade took with it.
        """

    @_abc_1.abstractmethod
    def ListNetworkMembers(
        self,
        request: _admin_pb2.ListNetworkMembersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ListNetworkMembersResponse, _abc.Awaitable[_admin_pb2.ListNetworkMembersResponse]]:
        """ListNetworkMembers returns the users assigned to a network."""

    @_abc_1.abstractmethod
    def AddNetworkMember(
        self,
        request: _admin_pb2.AddNetworkMemberRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.AddNetworkMemberResponse, _abc.Awaitable[_admin_pb2.AddNetworkMemberResponse]]:
        """AddNetworkMember assigns a user to a network. A user already placed in
        another network of the same domain is refused unless force is set, which
        relocates them.
        """

    @_abc_1.abstractmethod
    def RemoveNetworkMember(
        self,
        request: _admin_pb2.RemoveNetworkMemberRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.RemoveNetworkMemberResponse, _abc.Awaitable[_admin_pb2.RemoveNetworkMemberResponse]]:
        """RemoveNetworkMember unassigns a user from a network."""

    @_abc_1.abstractmethod
    def ListGroups(
        self,
        request: _admin_pb2.ListGroupsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ListGroupsResponse, _abc.Awaitable[_admin_pb2.ListGroupsResponse]]:
        """ListGroups returns one page of the organization's identity-provider groups.
        Available to enterprise organizations only.
        """

    @_abc_1.abstractmethod
    def ListGroupMembers(
        self,
        request: _admin_pb2.ListGroupMembersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ListGroupMembersResponse, _abc.Awaitable[_admin_pb2.ListGroupMembersResponse]]:
        """ListGroupMembers returns the users in an identity-provider group. Available
        to enterprise organizations only.
        """

    @_abc_1.abstractmethod
    def AddNetworkGroup(
        self,
        request: _admin_pb2.AddNetworkGroupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.AddNetworkGroupResponse, _abc.Awaitable[_admin_pb2.AddNetworkGroupResponse]]:
        """AddNetworkGroup assigns an identity-provider group to a network, which is how
        an enterprise organization places people in networks. A group holds one
        network per memory domain, so this replaces the group's network in the
        network's domain. Available to enterprise organizations only.
        """

    @_abc_1.abstractmethod
    def RemoveNetworkGroup(
        self,
        request: _admin_pb2.RemoveNetworkGroupRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.RemoveNetworkGroupResponse, _abc.Awaitable[_admin_pb2.RemoveNetworkGroupResponse]]:
        """RemoveNetworkGroup takes an identity-provider group out of a network. Its
        networks in other memory domains are unaffected. Available to enterprise
        organizations only.
        """

    @_abc_1.abstractmethod
    def ListExternalUsers(
        self,
        request: _admin_pb2.ListExternalUsersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ListExternalUsersResponse, _abc.Awaitable[_admin_pb2.ListExternalUsersResponse]]:
        """ListExternalUsers returns one page of the organization's external users."""

    @_abc_1.abstractmethod
    def GetExternalUser(
        self,
        request: _admin_pb2.GetExternalUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ExternalUser, _abc.Awaitable[_admin_pb2.ExternalUser]]:
        """GetExternalUser returns the external user with the external id."""

    @_abc_1.abstractmethod
    def CreateExternalUser(
        self,
        request: _admin_pb2.CreateExternalUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ExternalUser, _abc.Awaitable[_admin_pb2.ExternalUser]]:
        """CreateExternalUser adds an external user: a principal with no sign-in of its
        own, driven through API keys, holding reader, creator or auditor and never
        admin. It starts in no network; AddNetworkMember places it in a
        customer-scoped one.
        """

    @_abc_1.abstractmethod
    def UpdateExternalUser(
        self,
        request: _admin_pb2.UpdateExternalUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ExternalUser, _abc.Awaitable[_admin_pb2.ExternalUser]]:
        """UpdateExternalUser changes an external user's name, email or roles. The
        external id is immutable.
        """

    @_abc_1.abstractmethod
    def DeleteExternalUser(
        self,
        request: _admin_pb2.DeleteExternalUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.DeleteExternalUserResponse, _abc.Awaitable[_admin_pb2.DeleteExternalUserResponse]]:
        """DeleteExternalUser removes an external user and every key it holds."""

    @_abc_1.abstractmethod
    def ListExternalUserKeys(
        self,
        request: _admin_pb2.ListExternalUserKeysRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ListExternalUserKeysResponse, _abc.Awaitable[_admin_pb2.ListExternalUserKeysResponse]]:
        """ListExternalUserKeys returns an external user's API keys, without their values."""

    @_abc_1.abstractmethod
    def CreateExternalUserKey(
        self,
        request: _admin_pb2.CreateExternalUserKeyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.CreateExternalUserKeyResponse, _abc.Awaitable[_admin_pb2.CreateExternalUserKeyResponse]]:
        """CreateExternalUserKey mints an API key for an external user from a preset its
        roles allow, expiring within three months. The key is returned once.
        """

    @_abc_1.abstractmethod
    def DeleteExternalUserKey(
        self,
        request: _admin_pb2.DeleteExternalUserKeyRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.DeleteExternalUserKeyResponse, _abc.Awaitable[_admin_pb2.DeleteExternalUserKeyResponse]]:
        """DeleteExternalUserKey revokes one of an external user's API keys."""

    @_abc_1.abstractmethod
    def ImpersonateExternalUser(
        self,
        request: _admin_pb2.ImpersonateExternalUserRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.ImpersonationKey, _abc.Awaitable[_admin_pb2.ImpersonationKey]]:
        """ImpersonateExternalUser mints a short-lived key that acts as the external
        user, carrying its content role and, for an auditor, the audit stream. Only an
        API client holding the admin grant may call it.
        """

    @_abc_1.abstractmethod
    def EndImpersonation(
        self,
        request: _admin_pb2.EndImpersonationRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_admin_pb2.EndImpersonationResponse, _abc.Awaitable[_admin_pb2.EndImpersonationResponse]]:
        """EndImpersonation revokes an impersonation key before it expires."""

def add_AdminServiceServicer_to_server(servicer: AdminServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
