# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from memcoai.admin.v1 import admin_pb2 as memcoai_dot_admin_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memcoai/admin/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """AdminService is the organization-administration surface: the memory networks
    an organization places its people in, the identity-provider groups that place
    them in an enterprise organization, and the external users an organization
    drives through API keys.

    It is reached with a token from TokenService, and every call is bounded by the
    scope that token carries. The organization is always the credential's own — no
    request names one — so a token can never address another tenant.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNetworks = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ListNetworks',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworksRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworksResponse.FromString,
                _registered_method=True)
        self.CreateNetwork = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/CreateNetwork',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateNetworkRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.Network.FromString,
                _registered_method=True)
        self.UpdateNetwork = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/UpdateNetwork',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.UpdateNetworkRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.Network.FromString,
                _registered_method=True)
        self.DeleteNetwork = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/DeleteNetwork',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteNetworkRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteNetworkResponse.FromString,
                _registered_method=True)
        self.ListNetworkMembers = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ListNetworkMembers',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworkMembersRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworkMembersResponse.FromString,
                _registered_method=True)
        self.AddNetworkMember = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/AddNetworkMember',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkMemberRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkMemberResponse.FromString,
                _registered_method=True)
        self.RemoveNetworkMember = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/RemoveNetworkMember',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkMemberRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkMemberResponse.FromString,
                _registered_method=True)
        self.ListGroups = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ListGroups',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupsRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupsResponse.FromString,
                _registered_method=True)
        self.ListGroupMembers = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ListGroupMembers',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupMembersRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupMembersResponse.FromString,
                _registered_method=True)
        self.AddNetworkGroup = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/AddNetworkGroup',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkGroupRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkGroupResponse.FromString,
                _registered_method=True)
        self.RemoveNetworkGroup = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/RemoveNetworkGroup',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkGroupRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkGroupResponse.FromString,
                _registered_method=True)
        self.ListExternalUsers = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ListExternalUsers',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUsersRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUsersResponse.FromString,
                _registered_method=True)
        self.GetExternalUser = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/GetExternalUser',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.GetExternalUserRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.FromString,
                _registered_method=True)
        self.CreateExternalUser = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/CreateExternalUser',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.FromString,
                _registered_method=True)
        self.UpdateExternalUser = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/UpdateExternalUser',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.UpdateExternalUserRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.FromString,
                _registered_method=True)
        self.DeleteExternalUser = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/DeleteExternalUser',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserResponse.FromString,
                _registered_method=True)
        self.ListExternalUserKeys = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ListExternalUserKeys',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUserKeysRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUserKeysResponse.FromString,
                _registered_method=True)
        self.CreateExternalUserKey = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/CreateExternalUserKey',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserKeyRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserKeyResponse.FromString,
                _registered_method=True)
        self.DeleteExternalUserKey = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/DeleteExternalUserKey',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserKeyRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserKeyResponse.FromString,
                _registered_method=True)
        self.ImpersonateExternalUser = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/ImpersonateExternalUser',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ImpersonateExternalUserRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ImpersonationKey.FromString,
                _registered_method=True)
        self.EndImpersonation = channel.unary_unary(
                '/memcoai.admin.v1.AdminService/EndImpersonation',
                request_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.EndImpersonationRequest.SerializeToString,
                response_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.EndImpersonationResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """AdminService is the organization-administration surface: the memory networks
    an organization places its people in, the identity-provider groups that place
    them in an enterprise organization, and the external users an organization
    drives through API keys.

    It is reached with a token from TokenService, and every call is bounded by the
    scope that token carries. The organization is always the credential's own — no
    request names one — so a token can never address another tenant.
    """

    def ListNetworks(self, request, context):
        """ListNetworks returns one page of the organization's memory networks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNetwork(self, request, context):
        """CreateNetwork adds a memory network. A child takes its parent's domain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNetwork(self, request, context):
        """UpdateNetwork changes a network's name, parent, scope, owner or description.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNetwork(self, request, context):
        """DeleteNetwork removes a network and everything that hangs off it, reporting
        what the cascade took with it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNetworkMembers(self, request, context):
        """ListNetworkMembers returns the users assigned to a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNetworkMember(self, request, context):
        """AddNetworkMember assigns a user to a network. A user already placed in
        another network of the same domain is refused unless force is set, which
        relocates them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNetworkMember(self, request, context):
        """RemoveNetworkMember unassigns a user from a network.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGroups(self, request, context):
        """ListGroups returns one page of the organization's identity-provider groups.
        Available to enterprise organizations only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGroupMembers(self, request, context):
        """ListGroupMembers returns the users in an identity-provider group. Available
        to enterprise organizations only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNetworkGroup(self, request, context):
        """AddNetworkGroup assigns an identity-provider group to a network, which is how
        an enterprise organization places people in networks. A group holds one
        network per memory domain, so this replaces the group's network in the
        network's domain. Available to enterprise organizations only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNetworkGroup(self, request, context):
        """RemoveNetworkGroup takes an identity-provider group out of a network. Its
        networks in other memory domains are unaffected. Available to enterprise
        organizations only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExternalUsers(self, request, context):
        """ListExternalUsers returns one page of the organization's external users.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExternalUser(self, request, context):
        """GetExternalUser returns the external user with the external id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExternalUser(self, request, context):
        """CreateExternalUser adds an external user: a principal with no sign-in of its
        own, driven through API keys, holding reader, creator or auditor and never
        admin. It starts in no network; AddNetworkMember places it in a
        customer-scoped one.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateExternalUser(self, request, context):
        """UpdateExternalUser changes an external user's name, email or roles. The
        external id is immutable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExternalUser(self, request, context):
        """DeleteExternalUser removes an external user and every key it holds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExternalUserKeys(self, request, context):
        """ListExternalUserKeys returns an external user's API keys, without their values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExternalUserKey(self, request, context):
        """CreateExternalUserKey mints an API key for an external user from a preset its
        roles allow, expiring within three months. The key is returned once.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteExternalUserKey(self, request, context):
        """DeleteExternalUserKey revokes one of an external user's API keys.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImpersonateExternalUser(self, request, context):
        """ImpersonateExternalUser mints a short-lived key that acts as the external
        user, carrying its content role and, for an auditor, the audit stream. Only an
        API client holding the admin grant may call it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndImpersonation(self, request, context):
        """EndImpersonation revokes an impersonation key before it expires.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNetworks,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworksRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworksResponse.SerializeToString,
            ),
            'CreateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNetwork,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateNetworkRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.Network.SerializeToString,
            ),
            'UpdateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNetwork,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.UpdateNetworkRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.Network.SerializeToString,
            ),
            'DeleteNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNetwork,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteNetworkRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteNetworkResponse.SerializeToString,
            ),
            'ListNetworkMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNetworkMembers,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworkMembersRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworkMembersResponse.SerializeToString,
            ),
            'AddNetworkMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNetworkMember,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkMemberRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkMemberResponse.SerializeToString,
            ),
            'RemoveNetworkMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNetworkMember,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkMemberRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkMemberResponse.SerializeToString,
            ),
            'ListGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroups,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupsRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupsResponse.SerializeToString,
            ),
            'ListGroupMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGroupMembers,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupMembersRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupMembersResponse.SerializeToString,
            ),
            'AddNetworkGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNetworkGroup,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkGroupRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkGroupResponse.SerializeToString,
            ),
            'RemoveNetworkGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNetworkGroup,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkGroupRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkGroupResponse.SerializeToString,
            ),
            'ListExternalUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExternalUsers,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUsersRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUsersResponse.SerializeToString,
            ),
            'GetExternalUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExternalUser,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.GetExternalUserRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.SerializeToString,
            ),
            'CreateExternalUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExternalUser,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.SerializeToString,
            ),
            'UpdateExternalUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateExternalUser,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.UpdateExternalUserRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.SerializeToString,
            ),
            'DeleteExternalUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExternalUser,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserResponse.SerializeToString,
            ),
            'ListExternalUserKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExternalUserKeys,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUserKeysRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUserKeysResponse.SerializeToString,
            ),
            'CreateExternalUserKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExternalUserKey,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserKeyRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserKeyResponse.SerializeToString,
            ),
            'DeleteExternalUserKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteExternalUserKey,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserKeyRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserKeyResponse.SerializeToString,
            ),
            'ImpersonateExternalUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ImpersonateExternalUser,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ImpersonateExternalUserRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.ImpersonationKey.SerializeToString,
            ),
            'EndImpersonation': grpc.unary_unary_rpc_method_handler(
                    servicer.EndImpersonation,
                    request_deserializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.EndImpersonationRequest.FromString,
                    response_serializer=memcoai_dot_admin_dot_v1_dot_admin__pb2.EndImpersonationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memcoai.admin.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memcoai.admin.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """AdminService is the organization-administration surface: the memory networks
    an organization places its people in, the identity-provider groups that place
    them in an enterprise organization, and the external users an organization
    drives through API keys.

    It is reached with a token from TokenService, and every call is bounded by the
    scope that token carries. The organization is always the credential's own — no
    request names one — so a token can never address another tenant.
    """

    @staticmethod
    def ListNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ListNetworks',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworksRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/CreateNetwork',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateNetworkRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.Network.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/UpdateNetwork',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.UpdateNetworkRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.Network.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/DeleteNetwork',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteNetworkRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNetworkMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ListNetworkMembers',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworkMembersRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListNetworkMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNetworkMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/AddNetworkMember',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkMemberRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNetworkMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/RemoveNetworkMember',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkMemberRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ListGroups',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupsRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGroupMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ListGroupMembers',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupMembersRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListGroupMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNetworkGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/AddNetworkGroup',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkGroupRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.AddNetworkGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNetworkGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/RemoveNetworkGroup',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkGroupRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.RemoveNetworkGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExternalUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ListExternalUsers',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUsersRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExternalUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/GetExternalUser',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.GetExternalUserRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExternalUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/CreateExternalUser',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateExternalUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/UpdateExternalUser',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.UpdateExternalUserRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ExternalUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteExternalUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/DeleteExternalUser',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExternalUserKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ListExternalUserKeys',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUserKeysRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ListExternalUserKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExternalUserKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/CreateExternalUserKey',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserKeyRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.CreateExternalUserKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteExternalUserKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/DeleteExternalUserKey',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserKeyRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.DeleteExternalUserKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImpersonateExternalUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/ImpersonateExternalUser',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ImpersonateExternalUserRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.ImpersonationKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndImpersonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memcoai.admin.v1.AdminService/EndImpersonation',
            memcoai_dot_admin_dot_v1_dot_admin__pb2.EndImpersonationRequest.SerializeToString,
            memcoai_dot_admin_dot_v1_dot_admin__pb2.EndImpersonationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
