// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: memcoai/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Network is a memory network: the unit of knowledge scoping an organization
// places its people in.
type Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// parent_id is empty for a root network.
	ParentId string `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// domain is the memory domain the network's tree belongs to.
	Domain string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	// region is the network's data residency; "global" replicates everywhere.
	Region string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	// scope is "internal" or "customer", where the organization uses it.
	Scope string `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	// owner names who the network's knowledge belongs to, where it is used.
	Owner         string `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Description   string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Network) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Network) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Network) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Network) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Network) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Network) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ListNetworksRequest pages through the organization's networks.
type ListNetworksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name matches a network's name, case-insensitively.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// scope keeps networks of that scope: "internal", "customer" or "none".
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// owner matches a network's owner, case-insensitively.
	Owner    string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Page     int32  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// domain keeps networks of that memory domain.
	Domain string `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	// parent_id keeps the children of that network; "root" keeps root networks.
	ParentId string `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// ids keeps only those networks, at most 100.
	Ids           []string `protobuf:"bytes,8,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksRequest) Reset() {
	*x = ListNetworksRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksRequest) ProtoMessage() {}

func (x *ListNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksRequest.ProtoReflect.Descriptor instead.
func (*ListNetworksRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ListNetworksRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListNetworksRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListNetworksRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListNetworksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNetworksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNetworksRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListNetworksRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListNetworksRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// ListNetworksResponse is one page of networks.
type ListNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*Network             `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksResponse) Reset() {
	*x = ListNetworksResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksResponse) ProtoMessage() {}

func (x *ListNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksResponse.ProtoReflect.Descriptor instead.
func (*ListNetworksResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListNetworksResponse) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ListNetworksResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CreateNetworkRequest adds a network.
type CreateNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// parent_id makes this a child of another network, which it takes its domain
	// from. Empty creates a root.
	ParentId string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// domain places a root network; empty takes the organization's default. A child
	// must not name one.
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// region is the data residency; empty takes the organization's default.
	Region        string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Scope         string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Owner         string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Description   string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNetworkRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateNetworkRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateNetworkRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateNetworkRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateNetworkRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateNetworkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UpdateNetworkRequest patches a network. An unset field is left as it is; an
// explicitly empty string clears the field where the field can be cleared.
type UpdateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Scope         *string                `protobuf:"bytes,4,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	Owner         *string                `protobuf:"bytes,5,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNetworkRequest) Reset() {
	*x = UpdateNetworkRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNetworkRequest) ProtoMessage() {}

func (x *UpdateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNetworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNetworkRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateNetworkRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *UpdateNetworkRequest) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *UpdateNetworkRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *UpdateNetworkRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// DeleteNetworkRequest names the network to remove.
type DeleteNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteNetworkResponse reports what the cascade removed with the network, keyed
// by table, so a caller can see the cost of the deletion it just made.
type DeleteNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Removed       map[string]int64       `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkResponse) Reset() {
	*x = DeleteNetworkResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkResponse) ProtoMessage() {}

func (x *DeleteNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNetworkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteNetworkResponse) GetRemoved() map[string]int64 {
	if x != nil {
		return x.Removed
	}
	return nil
}

// Member is a user assigned to a network or a group.
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListNetworkMembersRequest pages through a network's members.
type ListNetworkMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkMembersRequest) Reset() {
	*x = ListNetworkMembersRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkMembersRequest) ProtoMessage() {}

func (x *ListNetworkMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkMembersRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkMembersRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListNetworkMembersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListNetworkMembersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListNetworkMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNetworkMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListNetworkMembersResponse is one page of members.
type ListNetworkMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkMembersResponse) Reset() {
	*x = ListNetworkMembersResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkMembersResponse) ProtoMessage() {}

func (x *ListNetworkMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkMembersResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkMembersResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListNetworkMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListNetworkMembersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// AddNetworkMemberRequest assigns a user to a network.
type AddNetworkMemberRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// force relocates a user already placed in another network of the same
	// domain. Without it such a request is refused, naming the network they are in.
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkMemberRequest) Reset() {
	*x = AddNetworkMemberRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkMemberRequest) ProtoMessage() {}

func (x *AddNetworkMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkMemberRequest.ProtoReflect.Descriptor instead.
func (*AddNetworkMemberRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AddNetworkMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddNetworkMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddNetworkMemberRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// AddNetworkMemberResponse reports the placement, including the network a moved
// user left.
type AddNetworkMemberResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// moved_from names the network the user was relocated out of, if any.
	MovedFrom     string `protobuf:"bytes,3,opt,name=moved_from,json=movedFrom,proto3" json:"moved_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkMemberResponse) Reset() {
	*x = AddNetworkMemberResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkMemberResponse) ProtoMessage() {}

func (x *AddNetworkMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkMemberResponse.ProtoReflect.Descriptor instead.
func (*AddNetworkMemberResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AddNetworkMemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddNetworkMemberResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddNetworkMemberResponse) GetMovedFrom() string {
	if x != nil {
		return x.MovedFrom
	}
	return ""
}

// RemoveNetworkMemberRequest unassigns a user from a network.
type RemoveNetworkMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkMemberRequest) Reset() {
	*x = RemoveNetworkMemberRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkMemberRequest) ProtoMessage() {}

func (x *RemoveNetworkMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveNetworkMemberRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveNetworkMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveNetworkMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RemoveNetworkMemberResponse is the acknowledgement of an unassignment.
type RemoveNetworkMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkMemberResponse) Reset() {
	*x = RemoveNetworkMemberResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkMemberResponse) ProtoMessage() {}

func (x *RemoveNetworkMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveNetworkMemberResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveNetworkMemberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveNetworkMemberResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Group is an identity-provider group of an enterprise organization. Its name
// and members are managed by the identity provider.
type Group struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// memory_network_id is the network the group's members are placed in; empty
	// when the group is assigned to none.
	MemoryNetworkId string `protobuf:"bytes,3,opt,name=memory_network_id,json=memoryNetworkId,proto3" json:"memory_network_id,omitempty"`
	MemberCount     int64  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetMemoryNetworkId() string {
	if x != nil {
		return x.MemoryNetworkId
	}
	return ""
}

func (x *Group) GetMemberCount() int64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

// ListGroupsRequest pages through the organization's groups.
type ListGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name matches a group's name, case-insensitively.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// network_id keeps groups bound to that network.
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// ids keeps only those groups, at most 100.
	Ids           []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	Page          int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32    `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListGroupsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListGroupsRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ListGroupsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListGroupsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGroupsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListGroupsResponse is one page of groups.
type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ListGroupMembersRequest names the group whose members to list.
type ListGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ListGroupMembersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListGroupMembersResponse is a group's members.
type ListGroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersResponse) Reset() {
	*x = ListGroupMembersResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse) ProtoMessage() {}

func (x *ListGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ListGroupMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// AddNetworkGroupRequest assigns a group to a network.
type AddNetworkGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkGroupRequest) Reset() {
	*x = AddNetworkGroupRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkGroupRequest) ProtoMessage() {}

func (x *AddNetworkGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkGroupRequest.ProtoReflect.Descriptor instead.
func (*AddNetworkGroupRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *AddNetworkGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddNetworkGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// AddNetworkGroupResponse is the acknowledgement of an assignment.
type AddNetworkGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkGroupResponse) Reset() {
	*x = AddNetworkGroupResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkGroupResponse) ProtoMessage() {}

func (x *AddNetworkGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkGroupResponse.ProtoReflect.Descriptor instead.
func (*AddNetworkGroupResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *AddNetworkGroupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddNetworkGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// RemoveNetworkGroupRequest takes a group out of a network.
type RemoveNetworkGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkGroupRequest) Reset() {
	*x = RemoveNetworkGroupRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkGroupRequest) ProtoMessage() {}

func (x *RemoveNetworkGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveNetworkGroupRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveNetworkGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveNetworkGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// RemoveNetworkGroupResponse is the acknowledgement of an unassignment.
type RemoveNetworkGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkGroupResponse) Reset() {
	*x = RemoveNetworkGroupResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkGroupResponse) ProtoMessage() {}

func (x *RemoveNetworkGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkGroupResponse.ProtoReflect.Descriptor instead.
func (*RemoveNetworkGroupResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveNetworkGroupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveNetworkGroupResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// ExternalUser is a principal the organization drives through API keys.
type ExternalUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// external_id is the caller's own identifier, unique within the organization.
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email      string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// roles are the content roles held: reader, creator and auditor.
	Roles         []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Active        bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalUser) Reset() {
	*x = ExternalUser{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalUser) ProtoMessage() {}

func (x *ExternalUser) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalUser.ProtoReflect.Descriptor instead.
func (*ExternalUser) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ExternalUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalUser) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ExternalUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExternalUser) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ExternalUser) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// ListExternalUsersRequest pages through the organization's external users.
type ListExternalUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// search matches the external id, name or email, case-insensitively.
	Search        string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalUsersRequest) Reset() {
	*x = ListExternalUsersRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalUsersRequest) ProtoMessage() {}

func (x *ListExternalUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalUsersRequest.ProtoReflect.Descriptor instead.
func (*ListExternalUsersRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ListExternalUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListExternalUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExternalUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListExternalUsersResponse is one page of external users.
type ListExternalUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalUsers []*ExternalUser        `protobuf:"bytes,1,rep,name=external_users,json=externalUsers,proto3" json:"external_users,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalUsersResponse) Reset() {
	*x = ListExternalUsersResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalUsersResponse) ProtoMessage() {}

func (x *ListExternalUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalUsersResponse.ProtoReflect.Descriptor instead.
func (*ListExternalUsersResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ListExternalUsersResponse) GetExternalUsers() []*ExternalUser {
	if x != nil {
		return x.ExternalUsers
	}
	return nil
}

func (x *ListExternalUsersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetExternalUserRequest names an external user.
type GetExternalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalUserRequest) Reset() {
	*x = GetExternalUserRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalUserRequest) ProtoMessage() {}

func (x *GetExternalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalUserRequest.ProtoReflect.Descriptor instead.
func (*GetExternalUserRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *GetExternalUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// CreateExternalUserRequest adds an external user.
type CreateExternalUserRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ExternalId string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email      string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// roles is a non-empty subset of reader, creator and auditor.
	Roles         []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExternalUserRequest) Reset() {
	*x = CreateExternalUserRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalUserRequest) ProtoMessage() {}

func (x *CreateExternalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalUserRequest.ProtoReflect.Descriptor instead.
func (*CreateExternalUserRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *CreateExternalUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CreateExternalUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExternalUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateExternalUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// UpdateExternalUserRequest patches an external user. An unset field is left as
// it is; roles, when given, replaces the role set.
type UpdateExternalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExternalUserRequest) Reset() {
	*x = UpdateExternalUserRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExternalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExternalUserRequest) ProtoMessage() {}

func (x *UpdateExternalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExternalUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateExternalUserRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateExternalUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UpdateExternalUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateExternalUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateExternalUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// DeleteExternalUserRequest names the external user to remove.
type DeleteExternalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExternalUserRequest) Reset() {
	*x = DeleteExternalUserRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExternalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExternalUserRequest) ProtoMessage() {}

func (x *DeleteExternalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExternalUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteExternalUserRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteExternalUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// DeleteExternalUserResponse is the acknowledgement of a removal.
type DeleteExternalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExternalUserResponse) Reset() {
	*x = DeleteExternalUserResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExternalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExternalUserResponse) ProtoMessage() {}

func (x *DeleteExternalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExternalUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteExternalUserResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteExternalUserResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// ExternalUserKey describes an API key without its value.
type ExternalUserKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// value_prefix is the key's first characters, to recognise it by.
	ValuePrefix string   `protobuf:"bytes,3,opt,name=value_prefix,json=valuePrefix,proto3" json:"value_prefix,omitempty"`
	Roles       []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Scopes      []string `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// valid_until is the expiry in Unix seconds.
	ValidUntil    int64 `protobuf:"varint,6,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalUserKey) Reset() {
	*x = ExternalUserKey{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalUserKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalUserKey) ProtoMessage() {}

func (x *ExternalUserKey) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalUserKey.ProtoReflect.Descriptor instead.
func (*ExternalUserKey) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *ExternalUserKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalUserKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalUserKey) GetValuePrefix() string {
	if x != nil {
		return x.ValuePrefix
	}
	return ""
}

func (x *ExternalUserKey) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ExternalUserKey) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ExternalUserKey) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

// ListExternalUserKeysRequest names the external user whose keys to list.
type ListExternalUserKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalUserKeysRequest) Reset() {
	*x = ListExternalUserKeysRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalUserKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalUserKeysRequest) ProtoMessage() {}

func (x *ListExternalUserKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalUserKeysRequest.ProtoReflect.Descriptor instead.
func (*ListExternalUserKeysRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *ListExternalUserKeysRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// ListExternalUserKeysResponse is an external user's keys.
type ListExternalUserKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*ExternalUserKey     `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalUserKeysResponse) Reset() {
	*x = ListExternalUserKeysResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalUserKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalUserKeysResponse) ProtoMessage() {}

func (x *ListExternalUserKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalUserKeysResponse.ProtoReflect.Descriptor instead.
func (*ListExternalUserKeysResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *ListExternalUserKeysResponse) GetKeys() []*ExternalUserKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// CreateExternalUserKeyRequest mints a key for an external user.
type CreateExternalUserKeyRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ExternalId string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// preset is "mcp_rw", "mcp_ro" or "audit", and must be within the external
	// user's roles.
	Preset string `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"`
	// valid_until is the expiry in Unix seconds, at most three months ahead; 0
	// takes three months.
	ValidUntil    int64 `protobuf:"varint,4,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExternalUserKeyRequest) Reset() {
	*x = CreateExternalUserKeyRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalUserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalUserKeyRequest) ProtoMessage() {}

func (x *CreateExternalUserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalUserKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateExternalUserKeyRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *CreateExternalUserKeyRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CreateExternalUserKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExternalUserKeyRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *CreateExternalUserKeyRequest) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

// CreateExternalUserKeyResponse carries the key, which is shown only here.
type CreateExternalUserKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *ExternalUserKey       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExternalUserKeyResponse) Reset() {
	*x = CreateExternalUserKeyResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExternalUserKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExternalUserKeyResponse) ProtoMessage() {}

func (x *CreateExternalUserKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExternalUserKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateExternalUserKeyResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{35}
}

func (x *CreateExternalUserKeyResponse) GetKey() *ExternalUserKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CreateExternalUserKeyResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// DeleteExternalUserKeyRequest names the key to revoke.
type DeleteExternalUserKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExternalUserKeyRequest) Reset() {
	*x = DeleteExternalUserKeyRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExternalUserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExternalUserKeyRequest) ProtoMessage() {}

func (x *DeleteExternalUserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExternalUserKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteExternalUserKeyRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteExternalUserKeyRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DeleteExternalUserKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// DeleteExternalUserKeyResponse is the acknowledgement of a revocation.
type DeleteExternalUserKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExternalUserKeyResponse) Reset() {
	*x = DeleteExternalUserKeyResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExternalUserKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExternalUserKeyResponse) ProtoMessage() {}

func (x *DeleteExternalUserKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExternalUserKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteExternalUserKeyResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteExternalUserKeyResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DeleteExternalUserKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// ImpersonateExternalUserRequest names the external user to act as.
type ImpersonateExternalUserRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ExternalId string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// ttl_minutes is the key's lifetime; 0 takes 60 minutes, and at most 1440.
	TtlMinutes    int32 `protobuf:"varint,2,opt,name=ttl_minutes,json=ttlMinutes,proto3" json:"ttl_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonateExternalUserRequest) Reset() {
	*x = ImpersonateExternalUserRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonateExternalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonateExternalUserRequest) ProtoMessage() {}

func (x *ImpersonateExternalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonateExternalUserRequest.ProtoReflect.Descriptor instead.
func (*ImpersonateExternalUserRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{38}
}

func (x *ImpersonateExternalUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ImpersonateExternalUserRequest) GetTtlMinutes() int32 {
	if x != nil {
		return x.TtlMinutes
	}
	return 0
}

// ImpersonationKey is a short-lived key acting as an external user. It is shown
// only here.
type ImpersonationKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// expires_at is the expiry in Unix seconds.
	ExpiresAt int64    `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Roles     []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Scopes    []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// key_id names the key to EndImpersonation.
	KeyId         string `protobuf:"bytes,5,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonationKey) Reset() {
	*x = ImpersonationKey{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonationKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonationKey) ProtoMessage() {}

func (x *ImpersonationKey) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonationKey.ProtoReflect.Descriptor instead.
func (*ImpersonationKey) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{39}
}

func (x *ImpersonationKey) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ImpersonationKey) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ImpersonationKey) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ImpersonationKey) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ImpersonationKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// EndImpersonationRequest names the impersonation key to revoke.
type EndImpersonationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndImpersonationRequest) Reset() {
	*x = EndImpersonationRequest{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndImpersonationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndImpersonationRequest) ProtoMessage() {}

func (x *EndImpersonationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndImpersonationRequest.ProtoReflect.Descriptor instead.
func (*EndImpersonationRequest) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{40}
}

func (x *EndImpersonationRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *EndImpersonationRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// EndImpersonationResponse is the acknowledgement of a revocation.
type EndImpersonationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndImpersonationResponse) Reset() {
	*x = EndImpersonationResponse{}
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndImpersonationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndImpersonationResponse) ProtoMessage() {}

func (x *EndImpersonationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memcoai_admin_v1_admin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndImpersonationResponse.ProtoReflect.Descriptor instead.
func (*EndImpersonationResponse) Descriptor() ([]byte, []int) {
	return file_memcoai_admin_v1_admin_proto_rawDescGZIP(), []int{41}
}

func (x *EndImpersonationResponse) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *EndImpersonationResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_memcoai_admin_v1_admin_proto protoreflect.FileDescriptor

const file_memcoai_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1cmemcoai/admin/v1/admin.proto\x12\x10memcoai.admin.v1\"\xc8\x01\n" +
	"\aNetwork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xcd\x01\n" +
	"\x13ListNetworksRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12\x10\n" +
	"\x03ids\x18\b \x03(\tR\x03ids\"n\n" +
	"\x14ListNetworksResponse\x125\n" +
	"\bnetworks\x18\x01 \x03(\v2\x19.memcoai.admin.v1.NetworkR\bnetworks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"\xc5\x01\n" +
	"\x14CreateNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xf9\x01\n" +
	"\x14UpdateNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x01R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05scope\x18\x04 \x01(\tH\x02R\x05scope\x88\x01\x01\x12\x19\n" +
	"\x05owner\x18\x05 \x01(\tH\x03R\x05owner\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x04R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_scopeB\b\n" +
	"\x06_ownerB\x0e\n" +
	"\f_description\"&\n" +
	"\x14DeleteNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb3\x01\n" +
	"\x15DeleteNetworkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12N\n" +
	"\aremoved\x18\x02 \x03(\v24.memcoai.admin.v1.DeleteNetworkResponse.RemovedEntryR\aremoved\x1a:\n" +
	"\fRemovedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"K\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"t\n" +
	"\x19ListNetworkMembersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"q\n" +
	"\x1aListNetworkMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.memcoai.admin.v1.MemberR\amembers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"X\n" +
	"\x17AddNetworkMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"b\n" +
	"\x18AddNetworkMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"moved_from\x18\x03 \x01(\tR\tmovedFrom\"E\n" +
	"\x1aRemoveNetworkMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"F\n" +
	"\x1bRemoveNetworkMemberResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"z\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11memory_network_id\x18\x03 \x01(\tR\x0fmemoryNetworkId\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x03R\vmemberCount\"\x89\x01\n" +
	"\x11ListGroupsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"f\n" +
	"\x12ListGroupsResponse\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.memcoai.admin.v1.GroupR\x06groups\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\")\n" +
	"\x17ListGroupMembersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x18ListGroupMembersResponse\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.memcoai.admin.v1.MemberR\amembers\"C\n" +
	"\x16AddNetworkGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"D\n" +
	"\x17AddNetworkGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"F\n" +
	"\x19RemoveNetworkGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"G\n" +
	"\x1aRemoveNetworkGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\x97\x01\n" +
	"\fExternalUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"c\n" +
	"\x18ListExternalUsersRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x83\x01\n" +
	"\x19ListExternalUsersResponse\x12E\n" +
	"\x0eexternal_users\x18\x01 \x03(\v2\x1e.memcoai.admin.v1.ExternalUserR\rexternalUsers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"9\n" +
	"\x16GetExternalUserRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"|\n" +
	"\x19CreateExternalUserRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\x99\x01\n" +
	"\x19UpdateExternalUserRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05rolesB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_email\"<\n" +
	"\x19DeleteExternalUserRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"=\n" +
	"\x1aDeleteExternalUserResponse\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"\xa7\x01\n" +
	"\x0fExternalUserKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fvalue_prefix\x18\x03 \x01(\tR\vvaluePrefix\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12\x1f\n" +
	"\vvalid_until\x18\x06 \x01(\x03R\n" +
	"validUntil\">\n" +
	"\x1bListExternalUserKeysRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"U\n" +
	"\x1cListExternalUserKeysResponse\x125\n" +
	"\x04keys\x18\x01 \x03(\v2!.memcoai.admin.v1.ExternalUserKeyR\x04keys\"\x8c\x01\n" +
	"\x1cCreateExternalUserKeyRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06preset\x18\x03 \x01(\tR\x06preset\x12\x1f\n" +
	"\vvalid_until\x18\x04 \x01(\x03R\n" +
	"validUntil\"j\n" +
	"\x1dCreateExternalUserKeyResponse\x123\n" +
	"\x03key\x18\x01 \x01(\v2!.memcoai.admin.v1.ExternalUserKeyR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"V\n" +
	"\x1cDeleteExternalUserKeyRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"W\n" +
	"\x1dDeleteExternalUserKeyResponse\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"b\n" +
	"\x1eImpersonateExternalUserRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vttl_minutes\x18\x02 \x01(\x05R\n" +
	"ttlMinutes\"\x8c\x01\n" +
	"\x10ImpersonationKey\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x15\n" +
	"\x06key_id\x18\x05 \x01(\tR\x05keyId\"Q\n" +
	"\x17EndImpersonationRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"R\n" +
	"\x18EndImpersonationResponse\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId2\xad\x11\n" +
	"\fAdminService\x12]\n" +
	"\fListNetworks\x12%.memcoai.admin.v1.ListNetworksRequest\x1a&.memcoai.admin.v1.ListNetworksResponse\x12R\n" +
	"\rCreateNetwork\x12&.memcoai.admin.v1.CreateNetworkRequest\x1a\x19.memcoai.admin.v1.Network\x12R\n" +
	"\rUpdateNetwork\x12&.memcoai.admin.v1.UpdateNetworkRequest\x1a\x19.memcoai.admin.v1.Network\x12`\n" +
	"\rDeleteNetwork\x12&.memcoai.admin.v1.DeleteNetworkRequest\x1a'.memcoai.admin.v1.DeleteNetworkResponse\x12o\n" +
	"\x12ListNetworkMembers\x12+.memcoai.admin.v1.ListNetworkMembersRequest\x1a,.memcoai.admin.v1.ListNetworkMembersResponse\x12i\n" +
	"\x10AddNetworkMember\x12).memcoai.admin.v1.AddNetworkMemberRequest\x1a*.memcoai.admin.v1.AddNetworkMemberResponse\x12r\n" +
	"\x13RemoveNetworkMember\x12,.memcoai.admin.v1.RemoveNetworkMemberRequest\x1a-.memcoai.admin.v1.RemoveNetworkMemberResponse\x12W\n" +
	"\n" +
	"ListGroups\x12#.memcoai.admin.v1.ListGroupsRequest\x1a$.memcoai.admin.v1.ListGroupsResponse\x12i\n" +
	"\x10ListGroupMembers\x12).memcoai.admin.v1.ListGroupMembersRequest\x1a*.memcoai.admin.v1.ListGroupMembersResponse\x12f\n" +
	"\x0fAddNetworkGroup\x12(.memcoai.admin.v1.AddNetworkGroupRequest\x1a).memcoai.admin.v1.AddNetworkGroupResponse\x12o\n" +
	"\x12RemoveNetworkGroup\x12+.memcoai.admin.v1.RemoveNetworkGroupRequest\x1a,.memcoai.admin.v1.RemoveNetworkGroupResponse\x12l\n" +
	"\x11ListExternalUsers\x12*.memcoai.admin.v1.ListExternalUsersRequest\x1a+.memcoai.admin.v1.ListExternalUsersResponse\x12[\n" +
	"\x0fGetExternalUser\x12(.memcoai.admin.v1.GetExternalUserRequest\x1a\x1e.memcoai.admin.v1.ExternalUser\x12a\n" +
	"\x12CreateExternalUser\x12+.memcoai.admin.v1.CreateExternalUserRequest\x1a\x1e.memcoai.admin.v1.ExternalUser\x12a\n" +
	"\x12UpdateExternalUser\x12+.memcoai.admin.v1.UpdateExternalUserRequest\x1a\x1e.memcoai.admin.v1.ExternalUser\x12o\n" +
	"\x12DeleteExternalUser\x12+.memcoai.admin.v1.DeleteExternalUserRequest\x1a,.memcoai.admin.v1.DeleteExternalUserResponse\x12u\n" +
	"\x14ListExternalUserKeys\x12-.memcoai.admin.v1.ListExternalUserKeysRequest\x1a..memcoai.admin.v1.ListExternalUserKeysResponse\x12x\n" +
	"\x15CreateExternalUserKey\x12..memcoai.admin.v1.CreateExternalUserKeyRequest\x1a/.memcoai.admin.v1.CreateExternalUserKeyResponse\x12x\n" +
	"\x15DeleteExternalUserKey\x12..memcoai.admin.v1.DeleteExternalUserKeyRequest\x1a/.memcoai.admin.v1.DeleteExternalUserKeyResponse\x12o\n" +
	"\x17ImpersonateExternalUser\x120.memcoai.admin.v1.ImpersonateExternalUserRequest\x1a\".memcoai.admin.v1.ImpersonationKey\x12i\n" +
	"\x10EndImpersonation\x12).memcoai.admin.v1.EndImpersonationRequest\x1a*.memcoai.admin.v1.EndImpersonationResponseBHZFgithub.com/memcoai/memcoai/go/internal/client/memcoai/admin/v1;adminv1b\x06proto3"

var (
	file_memcoai_admin_v1_admin_proto_rawDescOnce sync.Once
	file_memcoai_admin_v1_admin_proto_rawDescData []byte
)

func file_memcoai_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_memcoai_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_memcoai_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memcoai_admin_v1_admin_proto_rawDesc), len(file_memcoai_admin_v1_admin_proto_rawDesc)))
	})
	return file_memcoai_admin_v1_admin_proto_rawDescData
}

var file_memcoai_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_memcoai_admin_v1_admin_proto_goTypes = []any{
	(*Network)(nil),                        // 0: memcoai.admin.v1.Network
	(*ListNetworksRequest)(nil),            // 1: memcoai.admin.v1.ListNetworksRequest
	(*ListNetworksResponse)(nil),           // 2: memcoai.admin.v1.ListNetworksResponse
	(*CreateNetworkRequest)(nil),           // 3: memcoai.admin.v1.CreateNetworkRequest
	(*UpdateNetworkRequest)(nil),           // 4: memcoai.admin.v1.UpdateNetworkRequest
	(*DeleteNetworkRequest)(nil),           // 5: memcoai.admin.v1.DeleteNetworkRequest
	(*DeleteNetworkResponse)(nil),          // 6: memcoai.admin.v1.DeleteNetworkResponse
	(*Member)(nil),                         // 7: memcoai.admin.v1.Member
	(*ListNetworkMembersRequest)(nil),      // 8: memcoai.admin.v1.ListNetworkMembersRequest
	(*ListNetworkMembersResponse)(nil),     // 9: memcoai.admin.v1.ListNetworkMembersResponse
	(*AddNetworkMemberRequest)(nil),        // 10: memcoai.admin.v1.AddNetworkMemberRequest
	(*AddNetworkMemberResponse)(nil),       // 11: memcoai.admin.v1.AddNetworkMemberResponse
	(*RemoveNetworkMemberRequest)(nil),     // 12: memcoai.admin.v1.RemoveNetworkMemberRequest
	(*RemoveNetworkMemberResponse)(nil),    // 13: memcoai.admin.v1.RemoveNetworkMemberResponse
	(*Group)(nil),                          // 14: memcoai.admin.v1.Group
	(*ListGroupsRequest)(nil),              // 15: memcoai.admin.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),             // 16: memcoai.admin.v1.ListGroupsResponse
	(*ListGroupMembersRequest)(nil),        // 17: memcoai.admin.v1.ListGroupMembersRequest
	(*ListGroupMembersResponse)(nil),       // 18: memcoai.admin.v1.ListGroupMembersResponse
	(*AddNetworkGroupRequest)(nil),         // 19: memcoai.admin.v1.AddNetworkGroupRequest
	(*AddNetworkGroupResponse)(nil),        // 20: memcoai.admin.v1.AddNetworkGroupResponse
	(*RemoveNetworkGroupRequest)(nil),      // 21: memcoai.admin.v1.RemoveNetworkGroupRequest
	(*RemoveNetworkGroupResponse)(nil),     // 22: memcoai.admin.v1.RemoveNetworkGroupResponse
	(*ExternalUser)(nil),                   // 23: memcoai.admin.v1.ExternalUser
	(*ListExternalUsersRequest)(nil),       // 24: memcoai.admin.v1.ListExternalUsersRequest
	(*ListExternalUsersResponse)(nil),      // 25: memcoai.admin.v1.ListExternalUsersResponse
	(*GetExternalUserRequest)(nil),         // 26: memcoai.admin.v1.GetExternalUserRequest
	(*CreateExternalUserRequest)(nil),      // 27: memcoai.admin.v1.CreateExternalUserRequest
	(*UpdateExternalUserRequest)(nil),      // 28: memcoai.admin.v1.UpdateExternalUserRequest
	(*DeleteExternalUserRequest)(nil),      // 29: memcoai.admin.v1.DeleteExternalUserRequest
	(*DeleteExternalUserResponse)(nil),     // 30: memcoai.admin.v1.DeleteExternalUserResponse
	(*ExternalUserKey)(nil),                // 31: memcoai.admin.v1.ExternalUserKey
	(*ListExternalUserKeysRequest)(nil),    // 32: memcoai.admin.v1.ListExternalUserKeysRequest
	(*ListExternalUserKeysResponse)(nil),   // 33: memcoai.admin.v1.ListExternalUserKeysResponse
	(*CreateExternalUserKeyRequest)(nil),   // 34: memcoai.admin.v1.CreateExternalUserKeyRequest
	(*CreateExternalUserKeyResponse)(nil),  // 35: memcoai.admin.v1.CreateExternalUserKeyResponse
	(*DeleteExternalUserKeyRequest)(nil),   // 36: memcoai.admin.v1.DeleteExternalUserKeyRequest
	(*DeleteExternalUserKeyResponse)(nil),  // 37: memcoai.admin.v1.DeleteExternalUserKeyResponse
	(*ImpersonateExternalUserRequest)(nil), // 38: memcoai.admin.v1.ImpersonateExternalUserRequest
	(*ImpersonationKey)(nil),               // 39: memcoai.admin.v1.ImpersonationKey
	(*EndImpersonationRequest)(nil),        // 40: memcoai.admin.v1.EndImpersonationRequest
	(*EndImpersonationResponse)(nil),       // 41: memcoai.admin.v1.EndImpersonationResponse
	nil,                                    // 42: memcoai.admin.v1.DeleteNetworkResponse.RemovedEntry
}
var file_memcoai_admin_v1_admin_proto_depIdxs = []int32{
	0,  // 0: memcoai.admin.v1.ListNetworksResponse.networks:type_name -> memcoai.admin.v1.Network
	42, // 1: memcoai.admin.v1.DeleteNetworkResponse.removed:type_name -> memcoai.admin.v1.DeleteNetworkResponse.RemovedEntry
	7,  // 2: memcoai.admin.v1.ListNetworkMembersResponse.members:type_name -> memcoai.admin.v1.Member
	14, // 3: memcoai.admin.v1.ListGroupsResponse.groups:type_name -> memcoai.admin.v1.Group
	7,  // 4: memcoai.admin.v1.ListGroupMembersResponse.members:type_name -> memcoai.admin.v1.Member
	23, // 5: memcoai.admin.v1.ListExternalUsersResponse.external_users:type_name -> memcoai.admin.v1.ExternalUser
	31, // 6: memcoai.admin.v1.ListExternalUserKeysResponse.keys:type_name -> memcoai.admin.v1.ExternalUserKey
	31, // 7: memcoai.admin.v1.CreateExternalUserKeyResponse.key:type_name -> memcoai.admin.v1.ExternalUserKey
	1,  // 8: memcoai.admin.v1.AdminService.ListNetworks:input_type -> memcoai.admin.v1.ListNetworksRequest
	3,  // 9: memcoai.admin.v1.AdminService.CreateNetwork:input_type -> memcoai.admin.v1.CreateNetworkRequest
	4,  // 10: memcoai.admin.v1.AdminService.UpdateNetwork:input_type -> memcoai.admin.v1.UpdateNetworkRequest
	5,  // 11: memcoai.admin.v1.AdminService.DeleteNetwork:input_type -> memcoai.admin.v1.DeleteNetworkRequest
	8,  // 12: memcoai.admin.v1.AdminService.ListNetworkMembers:input_type -> memcoai.admin.v1.ListNetworkMembersRequest
	10, // 13: memcoai.admin.v1.AdminService.AddNetworkMember:input_type -> memcoai.admin.v1.AddNetworkMemberRequest
	12, // 14: memcoai.admin.v1.AdminService.RemoveNetworkMember:input_type -> memcoai.admin.v1.RemoveNetworkMemberRequest
	15, // 15: memcoai.admin.v1.AdminService.ListGroups:input_type -> memcoai.admin.v1.ListGroupsRequest
	17, // 16: memcoai.admin.v1.AdminService.ListGroupMembers:input_type -> memcoai.admin.v1.ListGroupMembersRequest
	19, // 17: memcoai.admin.v1.AdminService.AddNetworkGroup:input_type -> memcoai.admin.v1.AddNetworkGroupRequest
	21, // 18: memcoai.admin.v1.AdminService.RemoveNetworkGroup:input_type -> memcoai.admin.v1.RemoveNetworkGroupRequest
	24, // 19: memcoai.admin.v1.AdminService.ListExternalUsers:input_type -> memcoai.admin.v1.ListExternalUsersRequest
	26, // 20: memcoai.admin.v1.AdminService.GetExternalUser:input_type -> memcoai.admin.v1.GetExternalUserRequest
	27, // 21: memcoai.admin.v1.AdminService.CreateExternalUser:input_type -> memcoai.admin.v1.CreateExternalUserRequest
	28, // 22: memcoai.admin.v1.AdminService.UpdateExternalUser:input_type -> memcoai.admin.v1.UpdateExternalUserRequest
	29, // 23: memcoai.admin.v1.AdminService.DeleteExternalUser:input_type -> memcoai.admin.v1.DeleteExternalUserRequest
	32, // 24: memcoai.admin.v1.AdminService.ListExternalUserKeys:input_type -> memcoai.admin.v1.ListExternalUserKeysRequest
	34, // 25: memcoai.admin.v1.AdminService.CreateExternalUserKey:input_type -> memcoai.admin.v1.CreateExternalUserKeyRequest
	36, // 26: memcoai.admin.v1.AdminService.DeleteExternalUserKey:input_type -> memcoai.admin.v1.DeleteExternalUserKeyRequest
	38, // 27: memcoai.admin.v1.AdminService.ImpersonateExternalUser:input_type -> memcoai.admin.v1.ImpersonateExternalUserRequest
	40, // 28: memcoai.admin.v1.AdminService.EndImpersonation:input_type -> memcoai.admin.v1.EndImpersonationRequest
	2,  // 29: memcoai.admin.v1.AdminService.ListNetworks:output_type -> memcoai.admin.v1.ListNetworksResponse
	0,  // 30: memcoai.admin.v1.AdminService.CreateNetwork:output_type -> memcoai.admin.v1.Network
	0,  // 31: memcoai.admin.v1.AdminService.UpdateNetwork:output_type -> memcoai.admin.v1.Network
	6,  // 32: memcoai.admin.v1.AdminService.DeleteNetwork:output_type -> memcoai.admin.v1.DeleteNetworkResponse
	9,  // 33: memcoai.admin.v1.AdminService.ListNetworkMembers:output_type -> memcoai.admin.v1.ListNetworkMembersResponse
	11, // 34: memcoai.admin.v1.AdminService.AddNetworkMember:output_type -> memcoai.admin.v1.AddNetworkMemberResponse
	13, // 35: memcoai.admin.v1.AdminService.RemoveNetworkMember:output_type -> memcoai.admin.v1.RemoveNetworkMemberResponse
	16, // 36: memcoai.admin.v1.AdminService.ListGroups:output_type -> memcoai.admin.v1.ListGroupsResponse
	18, // 37: memcoai.admin.v1.AdminService.ListGroupMembers:output_type -> memcoai.admin.v1.ListGroupMembersResponse
	20, // 38: memcoai.admin.v1.AdminService.AddNetworkGroup:output_type -> memcoai.admin.v1.AddNetworkGroupResponse
	22, // 39: memcoai.admin.v1.AdminService.RemoveNetworkGroup:output_type -> memcoai.admin.v1.RemoveNetworkGroupResponse
	25, // 40: memcoai.admin.v1.AdminService.ListExternalUsers:output_type -> memcoai.admin.v1.ListExternalUsersResponse
	23, // 41: memcoai.admin.v1.AdminService.GetExternalUser:output_type -> memcoai.admin.v1.ExternalUser
	23, // 42: memcoai.admin.v1.AdminService.CreateExternalUser:output_type -> memcoai.admin.v1.ExternalUser
	23, // 43: memcoai.admin.v1.AdminService.UpdateExternalUser:output_type -> memcoai.admin.v1.ExternalUser
	30, // 44: memcoai.admin.v1.AdminService.DeleteExternalUser:output_type -> memcoai.admin.v1.DeleteExternalUserResponse
	33, // 45: memcoai.admin.v1.AdminService.ListExternalUserKeys:output_type -> memcoai.admin.v1.ListExternalUserKeysResponse
	35, // 46: memcoai.admin.v1.AdminService.CreateExternalUserKey:output_type -> memcoai.admin.v1.CreateExternalUserKeyResponse
	37, // 47: memcoai.admin.v1.AdminService.DeleteExternalUserKey:output_type -> memcoai.admin.v1.DeleteExternalUserKeyResponse
	39, // 48: memcoai.admin.v1.AdminService.ImpersonateExternalUser:output_type -> memcoai.admin.v1.ImpersonationKey
	41, // 49: memcoai.admin.v1.AdminService.EndImpersonation:output_type -> memcoai.admin.v1.EndImpersonationResponse
	29, // [29:50] is the sub-list for method output_type
	8,  // [8:29] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_memcoai_admin_v1_admin_proto_init() }
func file_memcoai_admin_v1_admin_proto_init() {
	if File_memcoai_admin_v1_admin_proto != nil {
		return
	}
	file_memcoai_admin_v1_admin_proto_msgTypes[4].OneofWrappers = []any{}
	file_memcoai_admin_v1_admin_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memcoai_admin_v1_admin_proto_rawDesc), len(file_memcoai_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memcoai_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_memcoai_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_memcoai_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_memcoai_admin_v1_admin_proto = out.File
	file_memcoai_admin_v1_admin_proto_goTypes = nil
	file_memcoai_admin_v1_admin_proto_depIdxs = nil
}
