// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: memcoai/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_ListNetworks_FullMethodName            = "/memcoai.admin.v1.AdminService/ListNetworks"
	AdminService_CreateNetwork_FullMethodName           = "/memcoai.admin.v1.AdminService/CreateNetwork"
	AdminService_UpdateNetwork_FullMethodName           = "/memcoai.admin.v1.AdminService/UpdateNetwork"
	AdminService_DeleteNetwork_FullMethodName           = "/memcoai.admin.v1.AdminService/DeleteNetwork"
	AdminService_ListNetworkMembers_FullMethodName      = "/memcoai.admin.v1.AdminService/ListNetworkMembers"
	AdminService_AddNetworkMember_FullMethodName        = "/memcoai.admin.v1.AdminService/AddNetworkMember"
	AdminService_RemoveNetworkMember_FullMethodName     = "/memcoai.admin.v1.AdminService/RemoveNetworkMember"
	AdminService_ListGroups_FullMethodName              = "/memcoai.admin.v1.AdminService/ListGroups"
	AdminService_ListGroupMembers_FullMethodName        = "/memcoai.admin.v1.AdminService/ListGroupMembers"
	AdminService_AddNetworkGroup_FullMethodName         = "/memcoai.admin.v1.AdminService/AddNetworkGroup"
	AdminService_RemoveNetworkGroup_FullMethodName      = "/memcoai.admin.v1.AdminService/RemoveNetworkGroup"
	AdminService_ListExternalUsers_FullMethodName       = "/memcoai.admin.v1.AdminService/ListExternalUsers"
	AdminService_GetExternalUser_FullMethodName         = "/memcoai.admin.v1.AdminService/GetExternalUser"
	AdminService_CreateExternalUser_FullMethodName      = "/memcoai.admin.v1.AdminService/CreateExternalUser"
	AdminService_UpdateExternalUser_FullMethodName      = "/memcoai.admin.v1.AdminService/UpdateExternalUser"
	AdminService_DeleteExternalUser_FullMethodName      = "/memcoai.admin.v1.AdminService/DeleteExternalUser"
	AdminService_ListExternalUserKeys_FullMethodName    = "/memcoai.admin.v1.AdminService/ListExternalUserKeys"
	AdminService_CreateExternalUserKey_FullMethodName   = "/memcoai.admin.v1.AdminService/CreateExternalUserKey"
	AdminService_DeleteExternalUserKey_FullMethodName   = "/memcoai.admin.v1.AdminService/DeleteExternalUserKey"
	AdminService_ImpersonateExternalUser_FullMethodName = "/memcoai.admin.v1.AdminService/ImpersonateExternalUser"
	AdminService_EndImpersonation_FullMethodName        = "/memcoai.admin.v1.AdminService/EndImpersonation"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the organization-administration surface: the memory networks
// an organization places its people in, the identity-provider groups that place
// them in an enterprise organization, and the external users an organization
// drives through API keys.
//
// It is reached with a token from TokenService, and every call is bounded by the
// scope that token carries. The organization is always the credential's own — no
// request names one — so a token can never address another tenant.
type AdminServiceClient interface {
	// ListNetworks returns one page of the organization's memory networks.
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	// CreateNetwork adds a memory network. A child takes its parent's domain.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*Network, error)
	// UpdateNetwork changes a network's name, parent, scope, owner or description.
	UpdateNetwork(ctx context.Context, in *UpdateNetworkRequest, opts ...grpc.CallOption) (*Network, error)
	// DeleteNetwork removes a network and everything that hangs off it, reporting
	// what the cascade took with it.
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	// ListNetworkMembers returns the users assigned to a network.
	ListNetworkMembers(ctx context.Context, in *ListNetworkMembersRequest, opts ...grpc.CallOption) (*ListNetworkMembersResponse, error)
	// AddNetworkMember assigns a user to a network. A user already placed in
	// another network of the same domain is refused unless force is set, which
	// relocates them.
	AddNetworkMember(ctx context.Context, in *AddNetworkMemberRequest, opts ...grpc.CallOption) (*AddNetworkMemberResponse, error)
	// RemoveNetworkMember unassigns a user from a network.
	RemoveNetworkMember(ctx context.Context, in *RemoveNetworkMemberRequest, opts ...grpc.CallOption) (*RemoveNetworkMemberResponse, error)
	// ListGroups returns one page of the organization's identity-provider groups.
	// Available to enterprise organizations only.
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	// ListGroupMembers returns the users in an identity-provider group. Available
	// to enterprise organizations only.
	ListGroupMembers(ctx context.Context, in *ListGroupMembersRequest, opts ...grpc.CallOption) (*ListGroupMembersResponse, error)
	// AddNetworkGroup assigns an identity-provider group to a network, which is how
	// an enterprise organization places people in networks. A group holds one
	// network per memory domain, so this replaces the group's network in the
	// network's domain. Available to enterprise organizations only.
	AddNetworkGroup(ctx context.Context, in *AddNetworkGroupRequest, opts ...grpc.CallOption) (*AddNetworkGroupResponse, error)
	// RemoveNetworkGroup takes an identity-provider group out of a network. Its
	// networks in other memory domains are unaffected. Available to enterprise
	// organizations only.
	RemoveNetworkGroup(ctx context.Context, in *RemoveNetworkGroupRequest, opts ...grpc.CallOption) (*RemoveNetworkGroupResponse, error)
	// ListExternalUsers returns one page of the organization's external users.
	ListExternalUsers(ctx context.Context, in *ListExternalUsersRequest, opts ...grpc.CallOption) (*ListExternalUsersResponse, error)
	// GetExternalUser returns the external user with the external id.
	GetExternalUser(ctx context.Context, in *GetExternalUserRequest, opts ...grpc.CallOption) (*ExternalUser, error)
	// CreateExternalUser adds an external user: a principal with no sign-in of its
	// own, driven through API keys, holding reader, creator or auditor and never
	// admin. It starts in no network; AddNetworkMember places it in a
	// customer-scoped one.
	CreateExternalUser(ctx context.Context, in *CreateExternalUserRequest, opts ...grpc.CallOption) (*ExternalUser, error)
	// UpdateExternalUser changes an external user's name, email or roles. The
	// external id is immutable.
	UpdateExternalUser(ctx context.Context, in *UpdateExternalUserRequest, opts ...grpc.CallOption) (*ExternalUser, error)
	// DeleteExternalUser removes an external user and every key it holds.
	DeleteExternalUser(ctx context.Context, in *DeleteExternalUserRequest, opts ...grpc.CallOption) (*DeleteExternalUserResponse, error)
	// ListExternalUserKeys returns an external user's API keys, without their values.
	ListExternalUserKeys(ctx context.Context, in *ListExternalUserKeysRequest, opts ...grpc.CallOption) (*ListExternalUserKeysResponse, error)
	// CreateExternalUserKey mints an API key for an external user from a preset its
	// roles allow, expiring within three months. The key is returned once.
	CreateExternalUserKey(ctx context.Context, in *CreateExternalUserKeyRequest, opts ...grpc.CallOption) (*CreateExternalUserKeyResponse, error)
	// DeleteExternalUserKey revokes one of an external user's API keys.
	DeleteExternalUserKey(ctx context.Context, in *DeleteExternalUserKeyRequest, opts ...grpc.CallOption) (*DeleteExternalUserKeyResponse, error)
	// ImpersonateExternalUser mints a short-lived key that acts as the external
	// user, carrying its content role and, for an auditor, the audit stream. Only an
	// API client holding the admin grant may call it.
	ImpersonateExternalUser(ctx context.Context, in *ImpersonateExternalUserRequest, opts ...grpc.CallOption) (*ImpersonationKey, error)
	// EndImpersonation revokes an impersonation key before it expires.
	EndImpersonation(ctx context.Context, in *EndImpersonationRequest, opts ...grpc.CallOption) (*EndImpersonationResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, AdminService_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*Network, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Network)
	err := c.cc.Invoke(ctx, AdminService_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateNetwork(ctx context.Context, in *UpdateNetworkRequest, opts ...grpc.CallOption) (*Network, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Network)
	err := c.cc.Invoke(ctx, AdminService_UpdateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListNetworkMembers(ctx context.Context, in *ListNetworkMembersRequest, opts ...grpc.CallOption) (*ListNetworkMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkMembersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListNetworkMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AddNetworkMember(ctx context.Context, in *AddNetworkMemberRequest, opts ...grpc.CallOption) (*AddNetworkMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNetworkMemberResponse)
	err := c.cc.Invoke(ctx, AdminService_AddNetworkMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveNetworkMember(ctx context.Context, in *RemoveNetworkMemberRequest, opts ...grpc.CallOption) (*RemoveNetworkMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNetworkMemberResponse)
	err := c.cc.Invoke(ctx, AdminService_RemoveNetworkMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListGroupMembers(ctx context.Context, in *ListGroupMembersRequest, opts ...grpc.CallOption) (*ListGroupMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupMembersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AddNetworkGroup(ctx context.Context, in *AddNetworkGroupRequest, opts ...grpc.CallOption) (*AddNetworkGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNetworkGroupResponse)
	err := c.cc.Invoke(ctx, AdminService_AddNetworkGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveNetworkGroup(ctx context.Context, in *RemoveNetworkGroupRequest, opts ...grpc.CallOption) (*RemoveNetworkGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNetworkGroupResponse)
	err := c.cc.Invoke(ctx, AdminService_RemoveNetworkGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListExternalUsers(ctx context.Context, in *ListExternalUsersRequest, opts ...grpc.CallOption) (*ListExternalUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExternalUsersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListExternalUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetExternalUser(ctx context.Context, in *GetExternalUserRequest, opts ...grpc.CallOption) (*ExternalUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalUser)
	err := c.cc.Invoke(ctx, AdminService_GetExternalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateExternalUser(ctx context.Context, in *CreateExternalUserRequest, opts ...grpc.CallOption) (*ExternalUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalUser)
	err := c.cc.Invoke(ctx, AdminService_CreateExternalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateExternalUser(ctx context.Context, in *UpdateExternalUserRequest, opts ...grpc.CallOption) (*ExternalUser, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalUser)
	err := c.cc.Invoke(ctx, AdminService_UpdateExternalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteExternalUser(ctx context.Context, in *DeleteExternalUserRequest, opts ...grpc.CallOption) (*DeleteExternalUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExternalUserResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteExternalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListExternalUserKeys(ctx context.Context, in *ListExternalUserKeysRequest, opts ...grpc.CallOption) (*ListExternalUserKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExternalUserKeysResponse)
	err := c.cc.Invoke(ctx, AdminService_ListExternalUserKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateExternalUserKey(ctx context.Context, in *CreateExternalUserKeyRequest, opts ...grpc.CallOption) (*CreateExternalUserKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExternalUserKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateExternalUserKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteExternalUserKey(ctx context.Context, in *DeleteExternalUserKeyRequest, opts ...grpc.CallOption) (*DeleteExternalUserKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExternalUserKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteExternalUserKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ImpersonateExternalUser(ctx context.Context, in *ImpersonateExternalUserRequest, opts ...grpc.CallOption) (*ImpersonationKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpersonationKey)
	err := c.cc.Invoke(ctx, AdminService_ImpersonateExternalUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EndImpersonation(ctx context.Context, in *EndImpersonationRequest, opts ...grpc.CallOption) (*EndImpersonationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndImpersonationResponse)
	err := c.cc.Invoke(ctx, AdminService_EndImpersonation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the organization-administration surface: the memory networks
// an organization places its people in, the identity-provider groups that place
// them in an enterprise organization, and the external users an organization
// drives through API keys.
//
// It is reached with a token from TokenService, and every call is bounded by the
// scope that token carries. The organization is always the credential's own — no
// request names one — so a token can never address another tenant.
type AdminServiceServer interface {
	// ListNetworks returns one page of the organization's memory networks.
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	// CreateNetwork adds a memory network. A child takes its parent's domain.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*Network, error)
	// UpdateNetwork changes a network's name, parent, scope, owner or description.
	UpdateNetwork(context.Context, *UpdateNetworkRequest) (*Network, error)
	// DeleteNetwork removes a network and everything that hangs off it, reporting
	// what the cascade took with it.
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	// ListNetworkMembers returns the users assigned to a network.
	ListNetworkMembers(context.Context, *ListNetworkMembersRequest) (*ListNetworkMembersResponse, error)
	// AddNetworkMember assigns a user to a network. A user already placed in
	// another network of the same domain is refused unless force is set, which
	// relocates them.
	AddNetworkMember(context.Context, *AddNetworkMemberRequest) (*AddNetworkMemberResponse, error)
	// RemoveNetworkMember unassigns a user from a network.
	RemoveNetworkMember(context.Context, *RemoveNetworkMemberRequest) (*RemoveNetworkMemberResponse, error)
	// ListGroups returns one page of the organization's identity-provider groups.
	// Available to enterprise organizations only.
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	// ListGroupMembers returns the users in an identity-provider group. Available
	// to enterprise organizations only.
	ListGroupMembers(context.Context, *ListGroupMembersRequest) (*ListGroupMembersResponse, error)
	// AddNetworkGroup assigns an identity-provider group to a network, which is how
	// an enterprise organization places people in networks. A group holds one
	// network per memory domain, so this replaces the group's network in the
	// network's domain. Available to enterprise organizations only.
	AddNetworkGroup(context.Context, *AddNetworkGroupRequest) (*AddNetworkGroupResponse, error)
	// RemoveNetworkGroup takes an identity-provider group out of a network. Its
	// networks in other memory domains are unaffected. Available to enterprise
	// organizations only.
	RemoveNetworkGroup(context.Context, *RemoveNetworkGroupRequest) (*RemoveNetworkGroupResponse, error)
	// ListExternalUsers returns one page of the organization's external users.
	ListExternalUsers(context.Context, *ListExternalUsersRequest) (*ListExternalUsersResponse, error)
	// GetExternalUser returns the external user with the external id.
	GetExternalUser(context.Context, *GetExternalUserRequest) (*ExternalUser, error)
	// CreateExternalUser adds an external user: a principal with no sign-in of its
	// own, driven through API keys, holding reader, creator or auditor and never
	// admin. It starts in no network; AddNetworkMember places it in a
	// customer-scoped one.
	CreateExternalUser(context.Context, *CreateExternalUserRequest) (*ExternalUser, error)
	// UpdateExternalUser changes an external user's name, email or roles. The
	// external id is immutable.
	UpdateExternalUser(context.Context, *UpdateExternalUserRequest) (*ExternalUser, error)
	// DeleteExternalUser removes an external user and every key it holds.
	DeleteExternalUser(context.Context, *DeleteExternalUserRequest) (*DeleteExternalUserResponse, error)
	// ListExternalUserKeys returns an external user's API keys, without their values.
	ListExternalUserKeys(context.Context, *ListExternalUserKeysRequest) (*ListExternalUserKeysResponse, error)
	// CreateExternalUserKey mints an API key for an external user from a preset its
	// roles allow, expiring within three months. The key is returned once.
	CreateExternalUserKey(context.Context, *CreateExternalUserKeyRequest) (*CreateExternalUserKeyResponse, error)
	// DeleteExternalUserKey revokes one of an external user's API keys.
	DeleteExternalUserKey(context.Context, *DeleteExternalUserKeyRequest) (*DeleteExternalUserKeyResponse, error)
	// ImpersonateExternalUser mints a short-lived key that acts as the external
	// user, carrying its content role and, for an auditor, the audit stream. Only an
	// API client holding the admin grant may call it.
	ImpersonateExternalUser(context.Context, *ImpersonateExternalUserRequest) (*ImpersonationKey, error)
	// EndImpersonation revokes an impersonation key before it expires.
	EndImpersonation(context.Context, *EndImpersonationRequest) (*EndImpersonationResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedAdminServiceServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*Network, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedAdminServiceServer) UpdateNetwork(context.Context, *UpdateNetworkRequest) (*Network, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNetwork not implemented")
}
func (UnimplementedAdminServiceServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedAdminServiceServer) ListNetworkMembers(context.Context, *ListNetworkMembersRequest) (*ListNetworkMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworkMembers not implemented")
}
func (UnimplementedAdminServiceServer) AddNetworkMember(context.Context, *AddNetworkMemberRequest) (*AddNetworkMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNetworkMember not implemented")
}
func (UnimplementedAdminServiceServer) RemoveNetworkMember(context.Context, *RemoveNetworkMemberRequest) (*RemoveNetworkMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNetworkMember not implemented")
}
func (UnimplementedAdminServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedAdminServiceServer) ListGroupMembers(context.Context, *ListGroupMembersRequest) (*ListGroupMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroupMembers not implemented")
}
func (UnimplementedAdminServiceServer) AddNetworkGroup(context.Context, *AddNetworkGroupRequest) (*AddNetworkGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNetworkGroup not implemented")
}
func (UnimplementedAdminServiceServer) RemoveNetworkGroup(context.Context, *RemoveNetworkGroupRequest) (*RemoveNetworkGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNetworkGroup not implemented")
}
func (UnimplementedAdminServiceServer) ListExternalUsers(context.Context, *ListExternalUsersRequest) (*ListExternalUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExternalUsers not implemented")
}
func (UnimplementedAdminServiceServer) GetExternalUser(context.Context, *GetExternalUserRequest) (*ExternalUser, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExternalUser not implemented")
}
func (UnimplementedAdminServiceServer) CreateExternalUser(context.Context, *CreateExternalUserRequest) (*ExternalUser, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExternalUser not implemented")
}
func (UnimplementedAdminServiceServer) UpdateExternalUser(context.Context, *UpdateExternalUserRequest) (*ExternalUser, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExternalUser not implemented")
}
func (UnimplementedAdminServiceServer) DeleteExternalUser(context.Context, *DeleteExternalUserRequest) (*DeleteExternalUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExternalUser not implemented")
}
func (UnimplementedAdminServiceServer) ListExternalUserKeys(context.Context, *ListExternalUserKeysRequest) (*ListExternalUserKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExternalUserKeys not implemented")
}
func (UnimplementedAdminServiceServer) CreateExternalUserKey(context.Context, *CreateExternalUserKeyRequest) (*CreateExternalUserKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExternalUserKey not implemented")
}
func (UnimplementedAdminServiceServer) DeleteExternalUserKey(context.Context, *DeleteExternalUserKeyRequest) (*DeleteExternalUserKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExternalUserKey not implemented")
}
func (UnimplementedAdminServiceServer) ImpersonateExternalUser(context.Context, *ImpersonateExternalUserRequest) (*ImpersonationKey, error) {
	return nil, status.Error(codes.Unimplemented, "method ImpersonateExternalUser not implemented")
}
func (UnimplementedAdminServiceServer) EndImpersonation(context.Context, *EndImpersonationRequest) (*EndImpersonationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndImpersonation not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateNetwork(ctx, req.(*UpdateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListNetworkMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListNetworkMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListNetworkMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListNetworkMembers(ctx, req.(*ListNetworkMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AddNetworkMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddNetworkMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddNetworkMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddNetworkMember(ctx, req.(*AddNetworkMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveNetworkMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNetworkMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveNetworkMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RemoveNetworkMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveNetworkMember(ctx, req.(*RemoveNetworkMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListGroupMembers(ctx, req.(*ListGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AddNetworkGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddNetworkGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AddNetworkGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddNetworkGroup(ctx, req.(*AddNetworkGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveNetworkGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNetworkGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveNetworkGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RemoveNetworkGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveNetworkGroup(ctx, req.(*RemoveNetworkGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListExternalUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExternalUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListExternalUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListExternalUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListExternalUsers(ctx, req.(*ListExternalUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetExternalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExternalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetExternalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetExternalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetExternalUser(ctx, req.(*GetExternalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateExternalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExternalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateExternalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateExternalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateExternalUser(ctx, req.(*CreateExternalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateExternalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExternalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateExternalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateExternalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateExternalUser(ctx, req.(*UpdateExternalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteExternalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExternalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteExternalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteExternalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteExternalUser(ctx, req.(*DeleteExternalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListExternalUserKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExternalUserKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListExternalUserKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListExternalUserKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListExternalUserKeys(ctx, req.(*ListExternalUserKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateExternalUserKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExternalUserKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateExternalUserKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateExternalUserKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateExternalUserKey(ctx, req.(*CreateExternalUserKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteExternalUserKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExternalUserKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteExternalUserKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteExternalUserKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteExternalUserKey(ctx, req.(*DeleteExternalUserKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ImpersonateExternalUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpersonateExternalUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ImpersonateExternalUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ImpersonateExternalUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ImpersonateExternalUser(ctx, req.(*ImpersonateExternalUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EndImpersonation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndImpersonationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EndImpersonation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_EndImpersonation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EndImpersonation(ctx, req.(*EndImpersonationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memcoai.admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNetworks",
			Handler:    _AdminService_ListNetworks_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _AdminService_CreateNetwork_Handler,
		},
		{
			MethodName: "UpdateNetwork",
			Handler:    _AdminService_UpdateNetwork_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _AdminService_DeleteNetwork_Handler,
		},
		{
			MethodName: "ListNetworkMembers",
			Handler:    _AdminService_ListNetworkMembers_Handler,
		},
		{
			MethodName: "AddNetworkMember",
			Handler:    _AdminService_AddNetworkMember_Handler,
		},
		{
			MethodName: "RemoveNetworkMember",
			Handler:    _AdminService_RemoveNetworkMember_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _AdminService_ListGroups_Handler,
		},
		{
			MethodName: "ListGroupMembers",
			Handler:    _AdminService_ListGroupMembers_Handler,
		},
		{
			MethodName: "AddNetworkGroup",
			Handler:    _AdminService_AddNetworkGroup_Handler,
		},
		{
			MethodName: "RemoveNetworkGroup",
			Handler:    _AdminService_RemoveNetworkGroup_Handler,
		},
		{
			MethodName: "ListExternalUsers",
			Handler:    _AdminService_ListExternalUsers_Handler,
		},
		{
			MethodName: "GetExternalUser",
			Handler:    _AdminService_GetExternalUser_Handler,
		},
		{
			MethodName: "CreateExternalUser",
			Handler:    _AdminService_CreateExternalUser_Handler,
		},
		{
			MethodName: "UpdateExternalUser",
			Handler:    _AdminService_UpdateExternalUser_Handler,
		},
		{
			MethodName: "DeleteExternalUser",
			Handler:    _AdminService_DeleteExternalUser_Handler,
		},
		{
			MethodName: "ListExternalUserKeys",
			Handler:    _AdminService_ListExternalUserKeys_Handler,
		},
		{
			MethodName: "CreateExternalUserKey",
			Handler:    _AdminService_CreateExternalUserKey_Handler,
		},
		{
			MethodName: "DeleteExternalUserKey",
			Handler:    _AdminService_DeleteExternalUserKey_Handler,
		},
		{
			MethodName: "ImpersonateExternalUser",
			Handler:    _AdminService_ImpersonateExternalUser_Handler,
		},
		{
			MethodName: "EndImpersonation",
			Handler:    _AdminService_EndImpersonation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memcoai/admin/v1/admin.proto",
}
