// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: memco/memory/v1/memory.proto

package memoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataSource names who produced the content. The operator source is written
// only by the memory operators and is deliberately absent: it is not a value a
// caller may claim.
type DataSource int32

const (
	// DATA_SOURCE_UNSPECIFIED is read as DATA_SOURCE_AGENT.
	DataSource_DATA_SOURCE_UNSPECIFIED DataSource = 0
	DataSource_DATA_SOURCE_USER        DataSource = 1
	DataSource_DATA_SOURCE_AGENT       DataSource = 2
)

// Enum value maps for DataSource.
var (
	DataSource_name = map[int32]string{
		0: "DATA_SOURCE_UNSPECIFIED",
		1: "DATA_SOURCE_USER",
		2: "DATA_SOURCE_AGENT",
	}
	DataSource_value = map[string]int32{
		"DATA_SOURCE_UNSPECIFIED": 0,
		"DATA_SOURCE_USER":        1,
		"DATA_SOURCE_AGENT":       2,
	}
)

func (x DataSource) Enum() *DataSource {
	p := new(DataSource)
	*p = x
	return p
}

func (x DataSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataSource) Descriptor() protoreflect.EnumDescriptor {
	return file_memco_memory_v1_memory_proto_enumTypes[0].Descriptor()
}

func (DataSource) Type() protoreflect.EnumType {
	return &file_memco_memory_v1_memory_proto_enumTypes[0]
}

func (x DataSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataSource.Descriptor instead.
func (DataSource) EnumDescriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

// RevertOutcome reports what a revert actually removed, so the caller is told
// what happened rather than what it had asked for. It names the effect, not the
// originating operation.
type RevertOutcome int32

const (
	RevertOutcome_REVERT_OUTCOME_UNSPECIFIED RevertOutcome = 0
	// The reverted insight was its memory's last, so the memory and its orphaned
	// intents went with it.
	RevertOutcome_REVERT_OUTCOME_MEMORY_REMOVED RevertOutcome = 1
	// Only the caller's insight was removed — its memory holds others and stays.
	RevertOutcome_REVERT_OUTCOME_ADDITION_REMOVED RevertOutcome = 2
	// The caller's insight was removed and no memory was involved either way — a
	// write the validator rejected never reaches one.
	RevertOutcome_REVERT_OUTCOME_ENTRY_REMOVED RevertOutcome = 3
	// The operation was folded into an existing insight as an endorsement rather
	// than added as new. The caller's duplicate was removed; the endorsed insight
	// is untouched.
	RevertOutcome_REVERT_OUTCOME_MERGED RevertOutcome = 4
	// No write by this caller carries the operation id — either it never existed
	// or its ingestion has not completed yet.
	RevertOutcome_REVERT_OUTCOME_NOT_FOUND RevertOutcome = 5
	// The operation is older than the revert window.
	RevertOutcome_REVERT_OUTCOME_EXPIRED RevertOutcome = 6
	// The content is under moderation and only a moderator may remove it.
	RevertOutcome_REVERT_OUTCOME_REFUSED RevertOutcome = 7
)

// Enum value maps for RevertOutcome.
var (
	RevertOutcome_name = map[int32]string{
		0: "REVERT_OUTCOME_UNSPECIFIED",
		1: "REVERT_OUTCOME_MEMORY_REMOVED",
		2: "REVERT_OUTCOME_ADDITION_REMOVED",
		3: "REVERT_OUTCOME_ENTRY_REMOVED",
		4: "REVERT_OUTCOME_MERGED",
		5: "REVERT_OUTCOME_NOT_FOUND",
		6: "REVERT_OUTCOME_EXPIRED",
		7: "REVERT_OUTCOME_REFUSED",
	}
	RevertOutcome_value = map[string]int32{
		"REVERT_OUTCOME_UNSPECIFIED":      0,
		"REVERT_OUTCOME_MEMORY_REMOVED":   1,
		"REVERT_OUTCOME_ADDITION_REMOVED": 2,
		"REVERT_OUTCOME_ENTRY_REMOVED":    3,
		"REVERT_OUTCOME_MERGED":           4,
		"REVERT_OUTCOME_NOT_FOUND":        5,
		"REVERT_OUTCOME_EXPIRED":          6,
		"REVERT_OUTCOME_REFUSED":          7,
	}
)

func (x RevertOutcome) Enum() *RevertOutcome {
	p := new(RevertOutcome)
	*p = x
	return p
}

func (x RevertOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RevertOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_memco_memory_v1_memory_proto_enumTypes[1].Descriptor()
}

func (RevertOutcome) Type() protoreflect.EnumType {
	return &file_memco_memory_v1_memory_proto_enumTypes[1]
}

func (x RevertOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RevertOutcome.Descriptor instead.
func (RevertOutcome) EnumDescriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{1}
}

// ImportStatus is what became of one memory of a batch.
type ImportStatus int32

const (
	ImportStatus_IMPORT_STATUS_UNSPECIFIED ImportStatus = 0
	// Accepted and queued for writing.
	ImportStatus_IMPORT_STATUS_QUEUED ImportStatus = 1
	// The entry itself was not usable; `errors` says what about it.
	ImportStatus_IMPORT_STATUS_REJECTED ImportStatus = 2
	// The entry was usable but could not be queued. Resubmitting it is the remedy;
	// an import is written under an identity derived from its own content, so a
	// memory that did land is not duplicated by sending it again.
	ImportStatus_IMPORT_STATUS_ERROR ImportStatus = 3
	// The content is already in memory, so nothing was written and nothing was
	// charged. Sending the same batch again is safe and free.
	ImportStatus_IMPORT_STATUS_DUPLICATE ImportStatus = 4
)

// Enum value maps for ImportStatus.
var (
	ImportStatus_name = map[int32]string{
		0: "IMPORT_STATUS_UNSPECIFIED",
		1: "IMPORT_STATUS_QUEUED",
		2: "IMPORT_STATUS_REJECTED",
		3: "IMPORT_STATUS_ERROR",
		4: "IMPORT_STATUS_DUPLICATE",
	}
	ImportStatus_value = map[string]int32{
		"IMPORT_STATUS_UNSPECIFIED": 0,
		"IMPORT_STATUS_QUEUED":      1,
		"IMPORT_STATUS_REJECTED":    2,
		"IMPORT_STATUS_ERROR":       3,
		"IMPORT_STATUS_DUPLICATE":   4,
	}
)

func (x ImportStatus) Enum() *ImportStatus {
	p := new(ImportStatus)
	*p = x
	return p
}

func (x ImportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_memco_memory_v1_memory_proto_enumTypes[2].Descriptor()
}

func (ImportStatus) Type() protoreflect.EnumType {
	return &file_memco_memory_v1_memory_proto_enumTypes[2]
}

func (x ImportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportStatus.Descriptor instead.
func (ImportStatus) EnumDescriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{2}
}

// Instructions is the model-facing guidance accompanying a result, held apart
// from the data so a caller can render its own document or use this one. Each
// part arrives already rendered for its domain; a part with nothing to say is
// empty.
type Instructions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content states what the result is, or what happened.
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// policy explains how a policy result outranks the rest. Present only when
	// one was returned.
	Policy string `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// adding says how to contribute back to what came back.
	Adding string `protobuf:"bytes,3,opt,name=adding,proto3" json:"adding,omitempty"`
	// rating says how to rate what came back.
	Rating string `protobuf:"bytes,4,opt,name=rating,proto3" json:"rating,omitempty"`
	// next names the follow-up call this result enables, such as the handle that
	// undoes a write.
	Next          string `protobuf:"bytes,5,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instructions) Reset() {
	*x = Instructions{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instructions) ProtoMessage() {}

func (x *Instructions) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instructions.ProtoReflect.Descriptor instead.
func (*Instructions) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Instructions) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Instructions) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *Instructions) GetAdding() string {
	if x != nil {
		return x.Adding
	}
	return ""
}

func (x *Instructions) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *Instructions) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

// Tag is one selector on a search or a write. The server lowercases each field
// and folds hyphens to underscores, so "Go" and "go" name the same tag.
//
// Which types exist, which of them narrow results rather than boost them, and
// which carry a version are per-domain: ListDomains describes them.
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the tag's category, such as "language" or "framework". Required.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// value is the value within that category, such as "go". Required.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// version is the version of the thing named, where its type carries one — a
	// version on a type that does not is dropped. Optional, and absent is the
	// common case: most tag types carry no version at all.
	Version       *string `protobuf:"bytes,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Tag) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

// DomainEntry describes one memory domain: what it holds, when to draw on it,
// what belongs in it, and the tag vocabulary it uses.
type DomainEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// slug is the value a caller passes as the domain field.
	Slug            string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title           string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary         string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	WhenToSearch    string `protobuf:"bytes,4,opt,name=when_to_search,json=whenToSearch,proto3" json:"when_to_search,omitempty"`
	WhenToSave      string `protobuf:"bytes,5,opt,name=when_to_save,json=whenToSave,proto3" json:"when_to_save,omitempty"`
	WhatNotToSave   string `protobuf:"bytes,6,opt,name=what_not_to_save,json=whatNotToSave,proto3" json:"what_not_to_save,omitempty"`
	TagsDescription string `protobuf:"bytes,7,opt,name=tags_description,json=tagsDescription,proto3" json:"tags_description,omitempty"`
	// filter_tag_types name the tag types that narrow results rather than boost
	// them — the distinction deciding whether a wrong tag returns nothing.
	FilterTagTypes []string `protobuf:"bytes,8,rep,name=filter_tag_types,json=filterTagTypes,proto3" json:"filter_tag_types,omitempty"`
	// version_tag_types name the tag types that carry a version. A version on any
	// other type is dropped.
	VersionTagTypes []string `protobuf:"bytes,9,rep,name=version_tag_types,json=versionTagTypes,proto3" json:"version_tag_types,omitempty"`
	// max_tags_per_query bounds `tags` on a call naming this domain. Like
	// max_sources it TRIMS rather than refuses, and it is per-domain rather than
	// global, which is why it sits here rather than on Limits. Zero means the
	// domain sets no cap.
	MaxTagsPerQuery int32 `protobuf:"varint,10,opt,name=max_tags_per_query,json=maxTagsPerQuery,proto3" json:"max_tags_per_query,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DomainEntry) Reset() {
	*x = DomainEntry{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEntry) ProtoMessage() {}

func (x *DomainEntry) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEntry.ProtoReflect.Descriptor instead.
func (*DomainEntry) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *DomainEntry) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DomainEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DomainEntry) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DomainEntry) GetWhenToSearch() string {
	if x != nil {
		return x.WhenToSearch
	}
	return ""
}

func (x *DomainEntry) GetWhenToSave() string {
	if x != nil {
		return x.WhenToSave
	}
	return ""
}

func (x *DomainEntry) GetWhatNotToSave() string {
	if x != nil {
		return x.WhatNotToSave
	}
	return ""
}

func (x *DomainEntry) GetTagsDescription() string {
	if x != nil {
		return x.TagsDescription
	}
	return ""
}

func (x *DomainEntry) GetFilterTagTypes() []string {
	if x != nil {
		return x.FilterTagTypes
	}
	return nil
}

func (x *DomainEntry) GetVersionTagTypes() []string {
	if x != nil {
		return x.VersionTagTypes
	}
	return nil
}

func (x *DomainEntry) GetMaxTagsPerQuery() int32 {
	if x != nil {
		return x.MaxTagsPerQuery
	}
	return 0
}

type DescribeDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeDomainsRequest) Reset() {
	*x = DescribeDomainsRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeDomainsRequest) ProtoMessage() {}

func (x *DescribeDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeDomainsRequest.ProtoReflect.Descriptor instead.
func (*DescribeDomainsRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{3}
}

type DescribeDomainsResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Domains      []*DomainEntry         `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	Instructions *Instructions          `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Limits       *Limits                `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	// deprecated marks what the caller is using as superseded — either this API
	// version, or the SDK build they are running. A client should surface it once
	// per process rather than per call.
	//
	// It does NOT say which of the two it is: that distinction lives in
	// deprecation_message, because only the server knows the remedy and only the
	// server can change the wording without an SDK release. Clients relay the
	// message; they should not try to infer a cause from the flag.
	//
	// This field ships before it is needed on purpose. A client can only be told
	// it is out of date if the version it was built against already carried the
	// field, so adding it when v2 arrives would reach only the callers who least
	// need telling.
	Deprecated bool `protobuf:"varint,4,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// deprecation_message is the server-authored remedy, empty when not
	// deprecated. It is the whole of what a client should show.
	DeprecationMessage string `protobuf:"bytes,5,opt,name=deprecation_message,json=deprecationMessage,proto3" json:"deprecation_message,omitempty"`
	// sunset_date is when what the caller uses stops working, as YYYY-MM-DD.
	// Empty when no date is set, which is not a promise that none will be.
	SunsetDate string `protobuf:"bytes,6,opt,name=sunset_date,json=sunsetDate,proto3" json:"sunset_date,omitempty"`
	// server_commit names the build that answered, so a caller can identify it in
	// a bug report.
	ServerCommit  string `protobuf:"bytes,7,opt,name=server_commit,json=serverCommit,proto3" json:"server_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeDomainsResponse) Reset() {
	*x = DescribeDomainsResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeDomainsResponse) ProtoMessage() {}

func (x *DescribeDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeDomainsResponse.ProtoReflect.Descriptor instead.
func (*DescribeDomainsResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeDomainsResponse) GetDomains() []*DomainEntry {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *DescribeDomainsResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *DescribeDomainsResponse) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *DescribeDomainsResponse) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *DescribeDomainsResponse) GetDeprecationMessage() string {
	if x != nil {
		return x.DeprecationMessage
	}
	return ""
}

func (x *DescribeDomainsResponse) GetSunsetDate() string {
	if x != nil {
		return x.SunsetDate
	}
	return ""
}

func (x *DescribeDomainsResponse) GetServerCommit() string {
	if x != nil {
		return x.ServerCommit
	}
	return ""
}

// Limits are the caps the server enforces, published so a client can check its
// input before spending a round trip on a call that would be refused.
//
// A server that predates this field sends no Limits at all. Treat that as
// "validate nothing" rather than as zeros, or every call is rejected locally.
//
// Note which caps REFUSE and which TRIM. A validator that raises on all of them
// rejects calls the server would have accepted.
type Limits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_query_characters bounds `query` on both Search and CreateMemory.
	// Exceeding it is refused with INVALID_ARGUMENT.
	MaxQueryCharacters int32 `protobuf:"varint,1,opt,name=max_query_characters,json=maxQueryCharacters,proto3" json:"max_query_characters,omitempty"`
	// max_text_characters bounds `title` and `content` TOGETHER, not each.
	// Exceeding it is refused with INVALID_ARGUMENT.
	MaxTextCharacters int32 `protobuf:"varint,2,opt,name=max_text_characters,json=maxTextCharacters,proto3" json:"max_text_characters,omitempty"`
	// max_idx_characters bounds any idx-shaped handle: `idx`, `memory_idx`, and
	// each entry of `sources`. Exceeding it is refused with INVALID_ARGUMENT.
	MaxIdxCharacters int32 `protobuf:"varint,3,opt,name=max_idx_characters,json=maxIdxCharacters,proto3" json:"max_idx_characters,omitempty"`
	// max_sources bounds `sources` on EnrichMemory. It TRIMS rather than refuses:
	// the server keeps the first max_sources and drops the rest, so a client
	// should trim too rather than raise.
	MaxSources int32 `protobuf:"varint,4,opt,name=max_sources,json=maxSources,proto3" json:"max_sources,omitempty"`
	// max_feedback_entries bounds `feedback` entries per ShareFeedback call.
	// Exceeding it is refused with INVALID_ARGUMENT.
	MaxFeedbackEntries int32 `protobuf:"varint,5,opt,name=max_feedback_entries,json=maxFeedbackEntries,proto3" json:"max_feedback_entries,omitempty"`
	// The four import caps. Each REFUSES rather than trims, so a client should
	// split a batch that exceeds one rather than send it and have it rejected.
	// max_import_memories bounds `memories` per ImportMemories call; the other
	// three bound one entry of it.
	MaxImportMemories          int32 `protobuf:"varint,6,opt,name=max_import_memories,json=maxImportMemories,proto3" json:"max_import_memories,omitempty"`
	MaxImportQueriesPerMemory  int32 `protobuf:"varint,7,opt,name=max_import_queries_per_memory,json=maxImportQueriesPerMemory,proto3" json:"max_import_queries_per_memory,omitempty"`
	MaxImportInsightsPerMemory int32 `protobuf:"varint,8,opt,name=max_import_insights_per_memory,json=maxImportInsightsPerMemory,proto3" json:"max_import_insights_per_memory,omitempty"`
	MaxImportTagsPerMemory     int32 `protobuf:"varint,9,opt,name=max_import_tags_per_memory,json=maxImportTagsPerMemory,proto3" json:"max_import_tags_per_memory,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *Limits) GetMaxQueryCharacters() int32 {
	if x != nil {
		return x.MaxQueryCharacters
	}
	return 0
}

func (x *Limits) GetMaxTextCharacters() int32 {
	if x != nil {
		return x.MaxTextCharacters
	}
	return 0
}

func (x *Limits) GetMaxIdxCharacters() int32 {
	if x != nil {
		return x.MaxIdxCharacters
	}
	return 0
}

func (x *Limits) GetMaxSources() int32 {
	if x != nil {
		return x.MaxSources
	}
	return 0
}

func (x *Limits) GetMaxFeedbackEntries() int32 {
	if x != nil {
		return x.MaxFeedbackEntries
	}
	return 0
}

func (x *Limits) GetMaxImportMemories() int32 {
	if x != nil {
		return x.MaxImportMemories
	}
	return 0
}

func (x *Limits) GetMaxImportQueriesPerMemory() int32 {
	if x != nil {
		return x.MaxImportQueriesPerMemory
	}
	return 0
}

func (x *Limits) GetMaxImportInsightsPerMemory() int32 {
	if x != nil {
		return x.MaxImportInsightsPerMemory
	}
	return 0
}

func (x *Limits) GetMaxImportTagsPerMemory() int32 {
	if x != nil {
		return x.MaxImportTagsPerMemory
	}
	return 0
}

type StartSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domain is required: a session belongs to one memory domain.
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *StartSessionRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Instructions  *Instructions          `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tags narrow or boost the results. Call ListDomains for the tag types a
	// domain uses and which of them filter rather than boost.
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// domain is required unless session_id is set, which supplies the domain of
	// the session it names.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// query is a task-based question, statement or task description.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// session_id records this search under an open session. Omitting it opens a
	// new one, returned as session_id on the response.
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *SearchRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SearchResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// memories holds what was selected, in rendered order. A search that selected
	// nothing leaves it empty.
	Memories []*MemoryResult `protobuf:"bytes,2,rep,name=memories,proto3" json:"memories,omitempty"`
	// notice is a remark about the query itself rather than about its results.
	Notice        string        `protobuf:"bytes,3,opt,name=notice,proto3" json:"notice,omitempty"`
	Instructions  *Instructions `protobuf:"bytes,4,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchResponse) GetMemories() []*MemoryResult {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *SearchResponse) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *SearchResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// MemoryResult is one memory a search returned, with the insights sampled from
// it.
type MemoryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Idx   string                 `protobuf:"bytes,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Kind  string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// times_served counts this delivery along with the previous ones. It records
	// deliveries and nothing else — a frequently served result is not thereby a
	// correct one, which is what endorsed and disputed answer.
	TimesServed int64 `protobuf:"varint,3,opt,name=times_served,json=timesServed,proto3" json:"times_served,omitempty"`
	// intents are the questions this memory has been retrieved by, oldest first.
	// They describe what it answers; none of them is "the one that matched",
	// since a memory is retrieved whole.
	Intents  []string         `protobuf:"bytes,4,rep,name=intents,proto3" json:"intents,omitempty"`
	Insights []*InsightResult `protobuf:"bytes,5,rep,name=insights,proto3" json:"insights,omitempty"`
	// reference names the idx an earlier search in this session returned this
	// memory under. An entry carrying one carries no insights: the memory is
	// already in the caller's context under that idx, and GetMemory returns it
	// again for a caller that never saw it.
	Reference     string `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResult) Reset() {
	*x = MemoryResult{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResult) ProtoMessage() {}

func (x *MemoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResult.ProtoReflect.Descriptor instead.
func (*MemoryResult) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{10}
}

func (x *MemoryResult) GetIdx() string {
	if x != nil {
		return x.Idx
	}
	return ""
}

func (x *MemoryResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MemoryResult) GetTimesServed() int64 {
	if x != nil {
		return x.TimesServed
	}
	return 0
}

func (x *MemoryResult) GetIntents() []string {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *MemoryResult) GetInsights() []*InsightResult {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *MemoryResult) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

// InsightResult is one insight held under its memory.
type InsightResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Idx     string                 `protobuf:"bytes,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Title   string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// updated is the day the insight was last written, as YYYY-MM-DD. Enrichment
	// edits an insight in place, so it is the age of the knowledge rather than of
	// the record.
	Updated     string `protobuf:"bytes,4,opt,name=updated,proto3" json:"updated,omitempty"`
	TimesServed int64  `protobuf:"varint,5,opt,name=times_served,json=timesServed,proto3" json:"times_served,omitempty"`
	// endorsed and disputed are what ShareFeedback has recorded about this
	// insight — the reliability signal times_served is not.
	Endorsed      int64 `protobuf:"varint,6,opt,name=endorsed,proto3" json:"endorsed,omitempty"`
	Disputed      int64 `protobuf:"varint,7,opt,name=disputed,proto3" json:"disputed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightResult) Reset() {
	*x = InsightResult{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightResult) ProtoMessage() {}

func (x *InsightResult) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightResult.ProtoReflect.Descriptor instead.
func (*InsightResult) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{11}
}

func (x *InsightResult) GetIdx() string {
	if x != nil {
		return x.Idx
	}
	return ""
}

func (x *InsightResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsightResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InsightResult) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *InsightResult) GetTimesServed() int64 {
	if x != nil {
		return x.TimesServed
	}
	return 0
}

func (x *InsightResult) GetEndorsed() int64 {
	if x != nil {
		return x.Endorsed
	}
	return 0
}

func (x *InsightResult) GetDisputed() int64 {
	if x != nil {
		return x.Disputed
	}
	return 0
}

type GetMemoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// idx is copied exactly as it appeared in a search response. An insight's idx
	// returns the memory holding it.
	Idx           string `protobuf:"bytes,1,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{12}
}

func (x *GetMemoryRequest) GetIdx() string {
	if x != nil {
		return x.Idx
	}
	return ""
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryResult          `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{13}
}

func (x *GetMemoryResponse) GetMemory() *MemoryResult {
	if x != nil {
		return x.Memory
	}
	return nil
}

type CreateMemoryRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tags   []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Source DataSource             `protobuf:"varint,2,opt,name=source,proto3,enum=memco.memory.v1.DataSource" json:"source,omitempty"`
	// domain is required unless session_id is set.
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// session_id names the session this memory was learned during.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// query describes what someone would search to find this memory.
	Query         string `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Title         string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content       string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryRequest) Reset() {
	*x = CreateMemoryRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryRequest) ProtoMessage() {}

func (x *CreateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{14}
}

func (x *CreateMemoryRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateMemoryRequest) GetSource() DataSource {
	if x != nil {
		return x.Source
	}
	return DataSource_DATA_SOURCE_UNSPECIFIED
}

func (x *CreateMemoryRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateMemoryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CreateMemoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMemoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// operation_id addresses the write, for RevertMemory. It is empty when none
	// could be minted: the content is worth more than the ability to undo it, so
	// numbering failure degrades to an un-revertible write rather than a
	// rejected one.
	OperationId   string        `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Instructions  *Instructions `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryResponse) Reset() {
	*x = CreateMemoryResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryResponse) ProtoMessage() {}

func (x *CreateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{15}
}

func (x *CreateMemoryResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreateMemoryResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type EnrichMemoryRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Tags    []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Source  DataSource             `protobuf:"varint,2,opt,name=source,proto3,enum=memco.memory.v1.DataSource" json:"source,omitempty"`
	Title   string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// sources name the memories this addition draws on.
	Sources []string `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	// session_id is required: the memory being enriched was returned by a search
	// under it, and the session supplies the domain.
	SessionId string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// memory_idx is the memory to enrich, or "new" to open one.
	MemoryIdx     string `protobuf:"bytes,7,opt,name=memory_idx,json=memoryIdx,proto3" json:"memory_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichMemoryRequest) Reset() {
	*x = EnrichMemoryRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichMemoryRequest) ProtoMessage() {}

func (x *EnrichMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichMemoryRequest.ProtoReflect.Descriptor instead.
func (*EnrichMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{16}
}

func (x *EnrichMemoryRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EnrichMemoryRequest) GetSource() DataSource {
	if x != nil {
		return x.Source
	}
	return DataSource_DATA_SOURCE_UNSPECIFIED
}

func (x *EnrichMemoryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EnrichMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EnrichMemoryRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EnrichMemoryRequest) GetMemoryIdx() string {
	if x != nil {
		return x.MemoryIdx
	}
	return ""
}

type EnrichMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Instructions  *Instructions          `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichMemoryResponse) Reset() {
	*x = EnrichMemoryResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichMemoryResponse) ProtoMessage() {}

func (x *EnrichMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichMemoryResponse.ProtoReflect.Descriptor instead.
func (*EnrichMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{17}
}

func (x *EnrichMemoryResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *EnrichMemoryResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type ShareFeedbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// feedback holds one rating per result being rated.
	Feedback []*FeedbackRating `protobuf:"bytes,1,rep,name=feedback,proto3" json:"feedback,omitempty"`
	// session_id is the search being rated. It supplies the domain.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFeedbackRequest) Reset() {
	*x = ShareFeedbackRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFeedbackRequest) ProtoMessage() {}

func (x *ShareFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFeedbackRequest.ProtoReflect.Descriptor instead.
func (*ShareFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{18}
}

func (x *ShareFeedbackRequest) GetFeedback() []*FeedbackRating {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ShareFeedbackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// FeedbackRating is one rating a caller gives a result.
type FeedbackRating struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// idx is copied exactly as it appeared in a search response, and cannot be
	// constructed by hand. An insight's idx rates that insight; a memory's own
	// idx rates every insight under it. Required.
	Idx string `protobuf:"bytes,1,opt,name=idx,proto3" json:"idx,omitempty"`
	// relevant reports whether the result was a good match for the query.
	Relevant bool `protobuf:"varint,2,opt,name=relevant,proto3" json:"relevant,omitempty"`
	// correct reports whether its content was accurate.
	Correct bool `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	// comment is an optional note about this result.
	Comment       *string `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackRating) Reset() {
	*x = FeedbackRating{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackRating) ProtoMessage() {}

func (x *FeedbackRating) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackRating.ProtoReflect.Descriptor instead.
func (*FeedbackRating) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{19}
}

func (x *FeedbackRating) GetIdx() string {
	if x != nil {
		return x.Idx
	}
	return ""
}

func (x *FeedbackRating) GetRelevant() bool {
	if x != nil {
		return x.Relevant
	}
	return false
}

func (x *FeedbackRating) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *FeedbackRating) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

type ShareFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Entries       []*FeedbackEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Instructions  *Instructions          `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFeedbackResponse) Reset() {
	*x = ShareFeedbackResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFeedbackResponse) ProtoMessage() {}

func (x *ShareFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFeedbackResponse.ProtoReflect.Descriptor instead.
func (*ShareFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{20}
}

func (x *ShareFeedbackResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShareFeedbackResponse) GetEntries() []*FeedbackEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ShareFeedbackResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// FeedbackEntry is one rating that was recorded.
type FeedbackEntry struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Idx      string                 `protobuf:"bytes,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Relevant bool                   `protobuf:"varint,2,opt,name=relevant,proto3" json:"relevant,omitempty"`
	Correct  bool                   `protobuf:"varint,3,opt,name=correct,proto3" json:"correct,omitempty"`
	// advice is the suggestion this particular verdict earned, empty when the
	// verdict suggests nothing. It addresses one result, so it belongs to the
	// entry rather than to the batch.
	Advice        string `protobuf:"bytes,4,opt,name=advice,proto3" json:"advice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackEntry) Reset() {
	*x = FeedbackEntry{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackEntry) ProtoMessage() {}

func (x *FeedbackEntry) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackEntry.ProtoReflect.Descriptor instead.
func (*FeedbackEntry) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{21}
}

func (x *FeedbackEntry) GetIdx() string {
	if x != nil {
		return x.Idx
	}
	return ""
}

func (x *FeedbackEntry) GetRelevant() bool {
	if x != nil {
		return x.Relevant
	}
	return false
}

func (x *FeedbackEntry) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *FeedbackEntry) GetAdvice() string {
	if x != nil {
		return x.Advice
	}
	return ""
}

type RevertMemoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// op_id is the operation id CreateMemory or EnrichMemory returned.
	OpId          string `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertMemoryRequest) Reset() {
	*x = RevertMemoryRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertMemoryRequest) ProtoMessage() {}

func (x *RevertMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertMemoryRequest.ProtoReflect.Descriptor instead.
func (*RevertMemoryRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{22}
}

func (x *RevertMemoryRequest) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

type RevertMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Outcome       RevertOutcome          `protobuf:"varint,2,opt,name=outcome,proto3,enum=memco.memory.v1.RevertOutcome" json:"outcome,omitempty"`
	Instructions  *Instructions          `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevertMemoryResponse) Reset() {
	*x = RevertMemoryResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertMemoryResponse) ProtoMessage() {}

func (x *RevertMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertMemoryResponse.ProtoReflect.Descriptor instead.
func (*RevertMemoryResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{23}
}

func (x *RevertMemoryResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RevertMemoryResponse) GetOutcome() RevertOutcome {
	if x != nil {
		return x.Outcome
	}
	return RevertOutcome_REVERT_OUTCOME_UNSPECIFIED
}

func (x *RevertMemoryResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type ImportMemoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// domain is required unless session_id is set, which supplies the domain of
	// the session it names. Every memory of the batch is imported into that one
	// domain; a batch cannot span domains.
	Domain   string            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Memories []*ImportedMemory `protobuf:"bytes,2,rep,name=memories,proto3" json:"memories,omitempty"`
	// session_id names the session this knowledge was contributed during, so a
	// batch gathered in the course of a task belongs to that series of work
	// rather than standing on its own. Omitting it files the memories under no
	// session, which is what a standalone upload wants.
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportMemoriesRequest) Reset() {
	*x = ImportMemoriesRequest{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportMemoriesRequest) ProtoMessage() {}

func (x *ImportMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ImportMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{24}
}

func (x *ImportMemoriesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ImportMemoriesRequest) GetMemories() []*ImportedMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *ImportMemoriesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ImportedMemory is one memory to contribute: what it should be found by, and
// what it holds.
type ImportedMemory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// queries are what someone would search to find this memory. At least one is
	// required.
	Queries []string `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	// insights are what the memory holds. At least one is required.
	Insights      []*ImportedInsight `protobuf:"bytes,2,rep,name=insights,proto3" json:"insights,omitempty"`
	Tags          []*Tag             `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedMemory) Reset() {
	*x = ImportedMemory{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedMemory) ProtoMessage() {}

func (x *ImportedMemory) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedMemory.ProtoReflect.Descriptor instead.
func (*ImportedMemory) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{25}
}

func (x *ImportedMemory) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ImportedMemory) GetInsights() []*ImportedInsight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *ImportedMemory) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ImportedInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedInsight) Reset() {
	*x = ImportedInsight{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedInsight) ProtoMessage() {}

func (x *ImportedInsight) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedInsight.ProtoReflect.Descriptor instead.
func (*ImportedInsight) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{26}
}

func (x *ImportedInsight) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImportedInsight) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ImportMemoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// results holds one entry per memory submitted, in the order they were sent.
	Results       []*ImportOutcome `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Instructions  *Instructions    `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportMemoriesResponse) Reset() {
	*x = ImportMemoriesResponse{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportMemoriesResponse) ProtoMessage() {}

func (x *ImportMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ImportMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{27}
}

func (x *ImportMemoriesResponse) GetResults() []*ImportOutcome {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ImportMemoriesResponse) GetInstructions() *Instructions {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// ImportOutcome is what happened to one memory of the batch, addressed by its
// position in the request: an import mints no handle a caller could name it by.
type ImportOutcome struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Index  int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Status ImportStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=memco.memory.v1.ImportStatus" json:"status,omitempty"`
	// errors says what was wrong with an entry that was not queued, and is empty
	// for one that was.
	Errors        []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOutcome) Reset() {
	*x = ImportOutcome{}
	mi := &file_memco_memory_v1_memory_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOutcome) ProtoMessage() {}

func (x *ImportOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_memco_memory_v1_memory_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOutcome.ProtoReflect.Descriptor instead.
func (*ImportOutcome) Descriptor() ([]byte, []int) {
	return file_memco_memory_v1_memory_proto_rawDescGZIP(), []int{28}
}

func (x *ImportOutcome) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ImportOutcome) GetStatus() ImportStatus {
	if x != nil {
		return x.Status
	}
	return ImportStatus_IMPORT_STATUS_UNSPECIFIED
}

func (x *ImportOutcome) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_memco_memory_v1_memory_proto protoreflect.FileDescriptor

const file_memco_memory_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x1cmemco/memory/v1/memory.proto\x12\x0fmemco.memory.v1\"\x84\x01\n" +
	"\fInstructions\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06policy\x18\x02 \x01(\tR\x06policy\x12\x16\n" +
	"\x06adding\x18\x03 \x01(\tR\x06adding\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\tR\x06rating\x12\x12\n" +
	"\x04next\x18\x05 \x01(\tR\x04next\"Z\n" +
	"\x03Tag\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\tH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"\xf0\x02\n" +
	"\vDomainEntry\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12$\n" +
	"\x0ewhen_to_search\x18\x04 \x01(\tR\fwhenToSearch\x12 \n" +
	"\fwhen_to_save\x18\x05 \x01(\tR\n" +
	"whenToSave\x12'\n" +
	"\x10what_not_to_save\x18\x06 \x01(\tR\rwhatNotToSave\x12)\n" +
	"\x10tags_description\x18\a \x01(\tR\x0ftagsDescription\x12(\n" +
	"\x10filter_tag_types\x18\b \x03(\tR\x0efilterTagTypes\x12*\n" +
	"\x11version_tag_types\x18\t \x03(\tR\x0fversionTagTypes\x12+\n" +
	"\x12max_tags_per_query\x18\n" +
	" \x01(\x05R\x0fmaxTagsPerQuery\"\x18\n" +
	"\x16DescribeDomainsRequest\"\xdc\x02\n" +
	"\x17DescribeDomainsResponse\x126\n" +
	"\adomains\x18\x01 \x03(\v2\x1c.memco.memory.v1.DomainEntryR\adomains\x12A\n" +
	"\finstructions\x18\x02 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\x12/\n" +
	"\x06limits\x18\x03 \x01(\v2\x17.memco.memory.v1.LimitsR\x06limits\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x04 \x01(\bR\n" +
	"deprecated\x12/\n" +
	"\x13deprecation_message\x18\x05 \x01(\tR\x12deprecationMessage\x12\x1f\n" +
	"\vsunset_date\x18\x06 \x01(\tR\n" +
	"sunsetDate\x12#\n" +
	"\rserver_commit\x18\a \x01(\tR\fserverCommit\"\xdd\x03\n" +
	"\x06Limits\x120\n" +
	"\x14max_query_characters\x18\x01 \x01(\x05R\x12maxQueryCharacters\x12.\n" +
	"\x13max_text_characters\x18\x02 \x01(\x05R\x11maxTextCharacters\x12,\n" +
	"\x12max_idx_characters\x18\x03 \x01(\x05R\x10maxIdxCharacters\x12\x1f\n" +
	"\vmax_sources\x18\x04 \x01(\x05R\n" +
	"maxSources\x120\n" +
	"\x14max_feedback_entries\x18\x05 \x01(\x05R\x12maxFeedbackEntries\x12.\n" +
	"\x13max_import_memories\x18\x06 \x01(\x05R\x11maxImportMemories\x12@\n" +
	"\x1dmax_import_queries_per_memory\x18\a \x01(\x05R\x19maxImportQueriesPerMemory\x12B\n" +
	"\x1emax_import_insights_per_memory\x18\b \x01(\x05R\x1amaxImportInsightsPerMemory\x12:\n" +
	"\x1amax_import_tags_per_memory\x18\t \x01(\x05R\x16maxImportTagsPerMemory\"-\n" +
	"\x13StartSessionRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"x\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12A\n" +
	"\finstructions\x18\x02 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"\x86\x01\n" +
	"\rSearchRequest\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x14.memco.memory.v1.TagR\x04tags\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\xc5\x01\n" +
	"\x0eSearchResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\bmemories\x18\x02 \x03(\v2\x1d.memco.memory.v1.MemoryResultR\bmemories\x12\x16\n" +
	"\x06notice\x18\x03 \x01(\tR\x06notice\x12A\n" +
	"\finstructions\x18\x04 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"\xcb\x01\n" +
	"\fMemoryResult\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\tR\x03idx\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12!\n" +
	"\ftimes_served\x18\x03 \x01(\x03R\vtimesServed\x12\x18\n" +
	"\aintents\x18\x04 \x03(\tR\aintents\x12:\n" +
	"\binsights\x18\x05 \x03(\v2\x1e.memco.memory.v1.InsightResultR\binsights\x12\x1c\n" +
	"\treference\x18\x06 \x01(\tR\treference\"\xc6\x01\n" +
	"\rInsightResult\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\tR\x03idx\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aupdated\x18\x04 \x01(\tR\aupdated\x12!\n" +
	"\ftimes_served\x18\x05 \x01(\x03R\vtimesServed\x12\x1a\n" +
	"\bendorsed\x18\x06 \x01(\x03R\bendorsed\x12\x1a\n" +
	"\bdisputed\x18\a \x01(\x03R\bdisputed\"$\n" +
	"\x10GetMemoryRequest\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\tR\x03idx\"J\n" +
	"\x11GetMemoryResponse\x125\n" +
	"\x06memory\x18\x01 \x01(\v2\x1d.memco.memory.v1.MemoryResultR\x06memory\"\xf1\x01\n" +
	"\x13CreateMemoryRequest\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x14.memco.memory.v1.TagR\x04tags\x123\n" +
	"\x06source\x18\x02 \x01(\x0e2\x1b.memco.memory.v1.DataSourceR\x06source\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"|\n" +
	"\x14CreateMemoryResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12A\n" +
	"\finstructions\x18\x02 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"\xfc\x01\n" +
	"\x13EnrichMemoryRequest\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x14.memco.memory.v1.TagR\x04tags\x123\n" +
	"\x06source\x18\x02 \x01(\x0e2\x1b.memco.memory.v1.DataSourceR\x06source\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x18\n" +
	"\asources\x18\x05 \x03(\tR\asources\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"memory_idx\x18\a \x01(\tR\tmemoryIdx\"|\n" +
	"\x14EnrichMemoryResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12A\n" +
	"\finstructions\x18\x02 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"r\n" +
	"\x14ShareFeedbackRequest\x12;\n" +
	"\bfeedback\x18\x01 \x03(\v2\x1f.memco.memory.v1.FeedbackRatingR\bfeedback\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x83\x01\n" +
	"\x0eFeedbackRating\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\tR\x03idx\x12\x1a\n" +
	"\brelevant\x18\x02 \x01(\bR\brelevant\x12\x18\n" +
	"\acorrect\x18\x03 \x01(\bR\acorrect\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x00R\acomment\x88\x01\x01B\n" +
	"\n" +
	"\b_comment\"\xb3\x01\n" +
	"\x15ShareFeedbackResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.memco.memory.v1.FeedbackEntryR\aentries\x12A\n" +
	"\finstructions\x18\x03 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"o\n" +
	"\rFeedbackEntry\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\tR\x03idx\x12\x1a\n" +
	"\brelevant\x18\x02 \x01(\bR\brelevant\x12\x18\n" +
	"\acorrect\x18\x03 \x01(\bR\acorrect\x12\x16\n" +
	"\x06advice\x18\x04 \x01(\tR\x06advice\"*\n" +
	"\x13RevertMemoryRequest\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\"\xb6\x01\n" +
	"\x14RevertMemoryResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x128\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x1e.memco.memory.v1.RevertOutcomeR\aoutcome\x12A\n" +
	"\finstructions\x18\x03 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"\x8b\x01\n" +
	"\x15ImportMemoriesRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12;\n" +
	"\bmemories\x18\x02 \x03(\v2\x1f.memco.memory.v1.ImportedMemoryR\bmemories\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x92\x01\n" +
	"\x0eImportedMemory\x12\x18\n" +
	"\aqueries\x18\x01 \x03(\tR\aqueries\x12<\n" +
	"\binsights\x18\x02 \x03(\v2 .memco.memory.v1.ImportedInsightR\binsights\x12(\n" +
	"\x04tags\x18\x03 \x03(\v2\x14.memco.memory.v1.TagR\x04tags\"A\n" +
	"\x0fImportedInsight\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x95\x01\n" +
	"\x16ImportMemoriesResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.memco.memory.v1.ImportOutcomeR\aresults\x12A\n" +
	"\finstructions\x18\x02 \x01(\v2\x1d.memco.memory.v1.InstructionsR\finstructions\"t\n" +
	"\rImportOutcome\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.memco.memory.v1.ImportStatusR\x06status\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors*V\n" +
	"\n" +
	"DataSource\x12\x1b\n" +
	"\x17DATA_SOURCE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DATA_SOURCE_USER\x10\x01\x12\x15\n" +
	"\x11DATA_SOURCE_AGENT\x10\x02*\x8a\x02\n" +
	"\rRevertOutcome\x12\x1e\n" +
	"\x1aREVERT_OUTCOME_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dREVERT_OUTCOME_MEMORY_REMOVED\x10\x01\x12#\n" +
	"\x1fREVERT_OUTCOME_ADDITION_REMOVED\x10\x02\x12 \n" +
	"\x1cREVERT_OUTCOME_ENTRY_REMOVED\x10\x03\x12\x19\n" +
	"\x15REVERT_OUTCOME_MERGED\x10\x04\x12\x1c\n" +
	"\x18REVERT_OUTCOME_NOT_FOUND\x10\x05\x12\x1a\n" +
	"\x16REVERT_OUTCOME_EXPIRED\x10\x06\x12\x1a\n" +
	"\x16REVERT_OUTCOME_REFUSED\x10\a*\x99\x01\n" +
	"\fImportStatus\x12\x1d\n" +
	"\x19IMPORT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14IMPORT_STATUS_QUEUED\x10\x01\x12\x1a\n" +
	"\x16IMPORT_STATUS_REJECTED\x10\x02\x12\x17\n" +
	"\x13IMPORT_STATUS_ERROR\x10\x03\x12\x1b\n" +
	"\x17IMPORT_STATUS_DUPLICATE\x10\x042\xcb\x06\n" +
	"\rMemoryService\x12d\n" +
	"\x0fDescribeDomains\x12'.memco.memory.v1.DescribeDomainsRequest\x1a(.memco.memory.v1.DescribeDomainsResponse\x12[\n" +
	"\fStartSession\x12$.memco.memory.v1.StartSessionRequest\x1a%.memco.memory.v1.StartSessionResponse\x12I\n" +
	"\x06Search\x12\x1e.memco.memory.v1.SearchRequest\x1a\x1f.memco.memory.v1.SearchResponse\x12R\n" +
	"\tGetMemory\x12!.memco.memory.v1.GetMemoryRequest\x1a\".memco.memory.v1.GetMemoryResponse\x12[\n" +
	"\fCreateMemory\x12$.memco.memory.v1.CreateMemoryRequest\x1a%.memco.memory.v1.CreateMemoryResponse\x12[\n" +
	"\fEnrichMemory\x12$.memco.memory.v1.EnrichMemoryRequest\x1a%.memco.memory.v1.EnrichMemoryResponse\x12^\n" +
	"\rShareFeedback\x12%.memco.memory.v1.ShareFeedbackRequest\x1a&.memco.memory.v1.ShareFeedbackResponse\x12[\n" +
	"\fRevertMemory\x12$.memco.memory.v1.RevertMemoryRequest\x1a%.memco.memory.v1.RevertMemoryResponse\x12a\n" +
	"\x0eImportMemories\x12&.memco.memory.v1.ImportMemoriesRequest\x1a'.memco.memory.v1.ImportMemoriesResponseB=Z;github.com/memcoai/memco/go/client/memco/memory/v1;memoryv1b\x06proto3"

var (
	file_memco_memory_v1_memory_proto_rawDescOnce sync.Once
	file_memco_memory_v1_memory_proto_rawDescData []byte
)

func file_memco_memory_v1_memory_proto_rawDescGZIP() []byte {
	file_memco_memory_v1_memory_proto_rawDescOnce.Do(func() {
		file_memco_memory_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memco_memory_v1_memory_proto_rawDesc), len(file_memco_memory_v1_memory_proto_rawDesc)))
	})
	return file_memco_memory_v1_memory_proto_rawDescData
}

var file_memco_memory_v1_memory_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_memco_memory_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_memco_memory_v1_memory_proto_goTypes = []any{
	(DataSource)(0),                 // 0: memco.memory.v1.DataSource
	(RevertOutcome)(0),              // 1: memco.memory.v1.RevertOutcome
	(ImportStatus)(0),               // 2: memco.memory.v1.ImportStatus
	(*Instructions)(nil),            // 3: memco.memory.v1.Instructions
	(*Tag)(nil),                     // 4: memco.memory.v1.Tag
	(*DomainEntry)(nil),             // 5: memco.memory.v1.DomainEntry
	(*DescribeDomainsRequest)(nil),  // 6: memco.memory.v1.DescribeDomainsRequest
	(*DescribeDomainsResponse)(nil), // 7: memco.memory.v1.DescribeDomainsResponse
	(*Limits)(nil),                  // 8: memco.memory.v1.Limits
	(*StartSessionRequest)(nil),     // 9: memco.memory.v1.StartSessionRequest
	(*StartSessionResponse)(nil),    // 10: memco.memory.v1.StartSessionResponse
	(*SearchRequest)(nil),           // 11: memco.memory.v1.SearchRequest
	(*SearchResponse)(nil),          // 12: memco.memory.v1.SearchResponse
	(*MemoryResult)(nil),            // 13: memco.memory.v1.MemoryResult
	(*InsightResult)(nil),           // 14: memco.memory.v1.InsightResult
	(*GetMemoryRequest)(nil),        // 15: memco.memory.v1.GetMemoryRequest
	(*GetMemoryResponse)(nil),       // 16: memco.memory.v1.GetMemoryResponse
	(*CreateMemoryRequest)(nil),     // 17: memco.memory.v1.CreateMemoryRequest
	(*CreateMemoryResponse)(nil),    // 18: memco.memory.v1.CreateMemoryResponse
	(*EnrichMemoryRequest)(nil),     // 19: memco.memory.v1.EnrichMemoryRequest
	(*EnrichMemoryResponse)(nil),    // 20: memco.memory.v1.EnrichMemoryResponse
	(*ShareFeedbackRequest)(nil),    // 21: memco.memory.v1.ShareFeedbackRequest
	(*FeedbackRating)(nil),          // 22: memco.memory.v1.FeedbackRating
	(*ShareFeedbackResponse)(nil),   // 23: memco.memory.v1.ShareFeedbackResponse
	(*FeedbackEntry)(nil),           // 24: memco.memory.v1.FeedbackEntry
	(*RevertMemoryRequest)(nil),     // 25: memco.memory.v1.RevertMemoryRequest
	(*RevertMemoryResponse)(nil),    // 26: memco.memory.v1.RevertMemoryResponse
	(*ImportMemoriesRequest)(nil),   // 27: memco.memory.v1.ImportMemoriesRequest
	(*ImportedMemory)(nil),          // 28: memco.memory.v1.ImportedMemory
	(*ImportedInsight)(nil),         // 29: memco.memory.v1.ImportedInsight
	(*ImportMemoriesResponse)(nil),  // 30: memco.memory.v1.ImportMemoriesResponse
	(*ImportOutcome)(nil),           // 31: memco.memory.v1.ImportOutcome
}
var file_memco_memory_v1_memory_proto_depIdxs = []int32{
	5,  // 0: memco.memory.v1.DescribeDomainsResponse.domains:type_name -> memco.memory.v1.DomainEntry
	3,  // 1: memco.memory.v1.DescribeDomainsResponse.instructions:type_name -> memco.memory.v1.Instructions
	8,  // 2: memco.memory.v1.DescribeDomainsResponse.limits:type_name -> memco.memory.v1.Limits
	3,  // 3: memco.memory.v1.StartSessionResponse.instructions:type_name -> memco.memory.v1.Instructions
	4,  // 4: memco.memory.v1.SearchRequest.tags:type_name -> memco.memory.v1.Tag
	13, // 5: memco.memory.v1.SearchResponse.memories:type_name -> memco.memory.v1.MemoryResult
	3,  // 6: memco.memory.v1.SearchResponse.instructions:type_name -> memco.memory.v1.Instructions
	14, // 7: memco.memory.v1.MemoryResult.insights:type_name -> memco.memory.v1.InsightResult
	13, // 8: memco.memory.v1.GetMemoryResponse.memory:type_name -> memco.memory.v1.MemoryResult
	4,  // 9: memco.memory.v1.CreateMemoryRequest.tags:type_name -> memco.memory.v1.Tag
	0,  // 10: memco.memory.v1.CreateMemoryRequest.source:type_name -> memco.memory.v1.DataSource
	3,  // 11: memco.memory.v1.CreateMemoryResponse.instructions:type_name -> memco.memory.v1.Instructions
	4,  // 12: memco.memory.v1.EnrichMemoryRequest.tags:type_name -> memco.memory.v1.Tag
	0,  // 13: memco.memory.v1.EnrichMemoryRequest.source:type_name -> memco.memory.v1.DataSource
	3,  // 14: memco.memory.v1.EnrichMemoryResponse.instructions:type_name -> memco.memory.v1.Instructions
	22, // 15: memco.memory.v1.ShareFeedbackRequest.feedback:type_name -> memco.memory.v1.FeedbackRating
	24, // 16: memco.memory.v1.ShareFeedbackResponse.entries:type_name -> memco.memory.v1.FeedbackEntry
	3,  // 17: memco.memory.v1.ShareFeedbackResponse.instructions:type_name -> memco.memory.v1.Instructions
	1,  // 18: memco.memory.v1.RevertMemoryResponse.outcome:type_name -> memco.memory.v1.RevertOutcome
	3,  // 19: memco.memory.v1.RevertMemoryResponse.instructions:type_name -> memco.memory.v1.Instructions
	28, // 20: memco.memory.v1.ImportMemoriesRequest.memories:type_name -> memco.memory.v1.ImportedMemory
	29, // 21: memco.memory.v1.ImportedMemory.insights:type_name -> memco.memory.v1.ImportedInsight
	4,  // 22: memco.memory.v1.ImportedMemory.tags:type_name -> memco.memory.v1.Tag
	31, // 23: memco.memory.v1.ImportMemoriesResponse.results:type_name -> memco.memory.v1.ImportOutcome
	3,  // 24: memco.memory.v1.ImportMemoriesResponse.instructions:type_name -> memco.memory.v1.Instructions
	2,  // 25: memco.memory.v1.ImportOutcome.status:type_name -> memco.memory.v1.ImportStatus
	6,  // 26: memco.memory.v1.MemoryService.DescribeDomains:input_type -> memco.memory.v1.DescribeDomainsRequest
	9,  // 27: memco.memory.v1.MemoryService.StartSession:input_type -> memco.memory.v1.StartSessionRequest
	11, // 28: memco.memory.v1.MemoryService.Search:input_type -> memco.memory.v1.SearchRequest
	15, // 29: memco.memory.v1.MemoryService.GetMemory:input_type -> memco.memory.v1.GetMemoryRequest
	17, // 30: memco.memory.v1.MemoryService.CreateMemory:input_type -> memco.memory.v1.CreateMemoryRequest
	19, // 31: memco.memory.v1.MemoryService.EnrichMemory:input_type -> memco.memory.v1.EnrichMemoryRequest
	21, // 32: memco.memory.v1.MemoryService.ShareFeedback:input_type -> memco.memory.v1.ShareFeedbackRequest
	25, // 33: memco.memory.v1.MemoryService.RevertMemory:input_type -> memco.memory.v1.RevertMemoryRequest
	27, // 34: memco.memory.v1.MemoryService.ImportMemories:input_type -> memco.memory.v1.ImportMemoriesRequest
	7,  // 35: memco.memory.v1.MemoryService.DescribeDomains:output_type -> memco.memory.v1.DescribeDomainsResponse
	10, // 36: memco.memory.v1.MemoryService.StartSession:output_type -> memco.memory.v1.StartSessionResponse
	12, // 37: memco.memory.v1.MemoryService.Search:output_type -> memco.memory.v1.SearchResponse
	16, // 38: memco.memory.v1.MemoryService.GetMemory:output_type -> memco.memory.v1.GetMemoryResponse
	18, // 39: memco.memory.v1.MemoryService.CreateMemory:output_type -> memco.memory.v1.CreateMemoryResponse
	20, // 40: memco.memory.v1.MemoryService.EnrichMemory:output_type -> memco.memory.v1.EnrichMemoryResponse
	23, // 41: memco.memory.v1.MemoryService.ShareFeedback:output_type -> memco.memory.v1.ShareFeedbackResponse
	26, // 42: memco.memory.v1.MemoryService.RevertMemory:output_type -> memco.memory.v1.RevertMemoryResponse
	30, // 43: memco.memory.v1.MemoryService.ImportMemories:output_type -> memco.memory.v1.ImportMemoriesResponse
	35, // [35:44] is the sub-list for method output_type
	26, // [26:35] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_memco_memory_v1_memory_proto_init() }
func file_memco_memory_v1_memory_proto_init() {
	if File_memco_memory_v1_memory_proto != nil {
		return
	}
	file_memco_memory_v1_memory_proto_msgTypes[1].OneofWrappers = []any{}
	file_memco_memory_v1_memory_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memco_memory_v1_memory_proto_rawDesc), len(file_memco_memory_v1_memory_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memco_memory_v1_memory_proto_goTypes,
		DependencyIndexes: file_memco_memory_v1_memory_proto_depIdxs,
		EnumInfos:         file_memco_memory_v1_memory_proto_enumTypes,
		MessageInfos:      file_memco_memory_v1_memory_proto_msgTypes,
	}.Build()
	File_memco_memory_v1_memory_proto = out.File
	file_memco_memory_v1_memory_proto_goTypes = nil
	file_memco_memory_v1_memory_proto_depIdxs = nil
}
