// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: memco/memory/v1/memory.proto

package memoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_ListDomains_FullMethodName    = "/memco.memory.v1.MemoryService/ListDomains"
	MemoryService_StartSession_FullMethodName   = "/memco.memory.v1.MemoryService/StartSession"
	MemoryService_Search_FullMethodName         = "/memco.memory.v1.MemoryService/Search"
	MemoryService_GetMemory_FullMethodName      = "/memco.memory.v1.MemoryService/GetMemory"
	MemoryService_CreateMemory_FullMethodName   = "/memco.memory.v1.MemoryService/CreateMemory"
	MemoryService_EnrichMemory_FullMethodName   = "/memco.memory.v1.MemoryService/EnrichMemory"
	MemoryService_ShareFeedback_FullMethodName  = "/memco.memory.v1.MemoryService/ShareFeedback"
	MemoryService_RevertMemory_FullMethodName   = "/memco.memory.v1.MemoryService/RevertMemory"
	MemoryService_ImportMemories_FullMethodName = "/memco.memory.v1.MemoryService/ImportMemories"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemoryService is the shared memory surface: the operations a client uses to
// find knowledge, contribute to it, and rate what it was given.
//
// Every identifier crossing this boundary is an external handle a previous
// response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
// id. A handle addresses the memory domain it belongs to, which is why most
// operations take no domain of their own.
type MemoryServiceClient interface {
	// ListDomains returns the memory domains the caller may name, together
	// with the limits the server enforces. It takes no domain itself: it is the
	// answer to "which domain?", and the one call a client makes before any other.
	ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error)
	// StartSession opens a session. Every search made under it is recorded as
	// one series, which is what relates the searches an agent runs for a task.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// Search retrieves memories for a task-based query, recording the search
	// against a session so it can be rated afterwards.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// GetMemory returns the memory behind an idx a search delivered, including
	// one returned as a reference to an earlier search in the same session.
	GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error)
	// CreateMemory saves new knowledge. It is accepted asynchronously, so the
	// response carries the operation id addressing the write rather than the
	// memory it will become.
	CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error)
	// EnrichMemory adds to a memory a search returned, or opens a new one.
	EnrichMemory(ctx context.Context, in *EnrichMemoryRequest, opts ...grpc.CallOption) (*EnrichMemoryResponse, error)
	// ShareFeedback rates the results of one search. Ratings are what move the
	// reliability signal on an insight.
	ShareFeedback(ctx context.Context, in *ShareFeedbackRequest, opts ...grpc.CallOption) (*ShareFeedbackResponse, error)
	// RevertMemory undoes the caller's own write, addressed by the operation id
	// that write returned. Every outcome is a successful call: expired, refused
	// and not_found report a caller-visible state, not a service failure.
	RevertMemory(ctx context.Context, in *RevertMemoryRequest, opts ...grpc.CallOption) (*RevertMemoryResponse, error)
	// ImportMemories contributes many memories in one call. Each becomes an
	// ordinary memory — evaluated on the way in and carrying the contributor's own
	// reliability, exactly as CreateMemory does — so this is a way to write a lot
	// at once, not a way to write differently.
	//
	// Every memory is judged on its own, so a refused entry does not stop the
	// others, and each is written asynchronously: the response reports what was
	// accepted rather than what now exists.
	//
	// A batch carries no operation id. RevertMemory addresses a single write, and
	// there is no handle that undoes an import.
	//
	// Naming a session records the batch against it, as CreateMemory and
	// EnrichMemory do, and supplies the domain the memories are imported into.
	ImportMemories(ctx context.Context, in *ImportMemoriesRequest, opts ...grpc.CallOption) (*ImportMemoriesResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainsResponse)
	err := c.cc.Invoke(ctx, MemoryService_ListDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, MemoryService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MemoryService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_CreateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) EnrichMemory(ctx context.Context, in *EnrichMemoryRequest, opts ...grpc.CallOption) (*EnrichMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_EnrichMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ShareFeedback(ctx context.Context, in *ShareFeedbackRequest, opts ...grpc.CallOption) (*ShareFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareFeedbackResponse)
	err := c.cc.Invoke(ctx, MemoryService_ShareFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) RevertMemory(ctx context.Context, in *RevertMemoryRequest, opts ...grpc.CallOption) (*RevertMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_RevertMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ImportMemories(ctx context.Context, in *ImportMemoriesRequest, opts ...grpc.CallOption) (*ImportMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportMemoriesResponse)
	err := c.cc.Invoke(ctx, MemoryService_ImportMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
//
// MemoryService is the shared memory surface: the operations a client uses to
// find knowledge, contribute to it, and rate what it was given.
//
// Every identifier crossing this boundary is an external handle a previous
// response issued — "session-<h>", "create-<h>", "memory-<h>-N" — never a row
// id. A handle addresses the memory domain it belongs to, which is why most
// operations take no domain of their own.
type MemoryServiceServer interface {
	// ListDomains returns the memory domains the caller may name, together
	// with the limits the server enforces. It takes no domain itself: it is the
	// answer to "which domain?", and the one call a client makes before any other.
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
	// StartSession opens a session. Every search made under it is recorded as
	// one series, which is what relates the searches an agent runs for a task.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// Search retrieves memories for a task-based query, recording the search
	// against a session so it can be rated afterwards.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// GetMemory returns the memory behind an idx a search delivered, including
	// one returned as a reference to an earlier search in the same session.
	GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error)
	// CreateMemory saves new knowledge. It is accepted asynchronously, so the
	// response carries the operation id addressing the write rather than the
	// memory it will become.
	CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error)
	// EnrichMemory adds to a memory a search returned, or opens a new one.
	EnrichMemory(context.Context, *EnrichMemoryRequest) (*EnrichMemoryResponse, error)
	// ShareFeedback rates the results of one search. Ratings are what move the
	// reliability signal on an insight.
	ShareFeedback(context.Context, *ShareFeedbackRequest) (*ShareFeedbackResponse, error)
	// RevertMemory undoes the caller's own write, addressed by the operation id
	// that write returned. Every outcome is a successful call: expired, refused
	// and not_found report a caller-visible state, not a service failure.
	RevertMemory(context.Context, *RevertMemoryRequest) (*RevertMemoryResponse, error)
	// ImportMemories contributes many memories in one call. Each becomes an
	// ordinary memory — evaluated on the way in and carrying the contributor's own
	// reliability, exactly as CreateMemory does — so this is a way to write a lot
	// at once, not a way to write differently.
	//
	// Every memory is judged on its own, so a refused entry does not stop the
	// others, and each is written asynchronously: the response reports what was
	// accepted rather than what now exists.
	//
	// A batch carries no operation id. RevertMemory addresses a single write, and
	// there is no handle that undoes an import.
	//
	// Naming a session records the batch against it, as CreateMemory and
	// EnrichMemory do, and supplies the domain the memories are imported into.
	ImportMemories(context.Context, *ImportMemoriesRequest) (*ImportMemoriesResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDomains not implemented")
}
func (UnimplementedMemoryServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedMemoryServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMemoryServiceServer) GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemory not implemented")
}
func (UnimplementedMemoryServiceServer) CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMemory not implemented")
}
func (UnimplementedMemoryServiceServer) EnrichMemory(context.Context, *EnrichMemoryRequest) (*EnrichMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichMemory not implemented")
}
func (UnimplementedMemoryServiceServer) ShareFeedback(context.Context, *ShareFeedbackRequest) (*ShareFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareFeedback not implemented")
}
func (UnimplementedMemoryServiceServer) RevertMemory(context.Context, *RevertMemoryRequest) (*RevertMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevertMemory not implemented")
}
func (UnimplementedMemoryServiceServer) ImportMemories(context.Context, *ImportMemoriesRequest) (*ImportMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportMemories not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call panics, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ListDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ListDomains(ctx, req.(*ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetMemory(ctx, req.(*GetMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_CreateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).CreateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_CreateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).CreateMemory(ctx, req.(*CreateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_EnrichMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).EnrichMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_EnrichMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).EnrichMemory(ctx, req.(*EnrichMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ShareFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ShareFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ShareFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ShareFeedback(ctx, req.(*ShareFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_RevertMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).RevertMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_RevertMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).RevertMemory(ctx, req.(*RevertMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ImportMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ImportMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ImportMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ImportMemories(ctx, req.(*ImportMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memco.memory.v1.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDomains",
			Handler:    _MemoryService_ListDomains_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _MemoryService_StartSession_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MemoryService_Search_Handler,
		},
		{
			MethodName: "GetMemory",
			Handler:    _MemoryService_GetMemory_Handler,
		},
		{
			MethodName: "CreateMemory",
			Handler:    _MemoryService_CreateMemory_Handler,
		},
		{
			MethodName: "EnrichMemory",
			Handler:    _MemoryService_EnrichMemory_Handler,
		},
		{
			MethodName: "ShareFeedback",
			Handler:    _MemoryService_ShareFeedback_Handler,
		},
		{
			MethodName: "RevertMemory",
			Handler:    _MemoryService_RevertMemory_Handler,
		},
		{
			MethodName: "ImportMemories",
			Handler:    _MemoryService_ImportMemories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memco/memory/v1/memory.proto",
}
