"""The provenance descriptor shipped inside the package."""

import hashlib
import pathlib

import pytest

from memco._provenance import parse, provenance
from memco.errors import ClientConfigError

REPO = pathlib.Path(__file__).resolve().parents[2]


def test_provenance_is_readable_from_the_installed_package():
    p = provenance()
    assert p.server_commit
    assert p.protos
    assert p.protos[0].path == "memco/memory/v1/memory.proto"


def test_provenance_is_cached():
    assert provenance() is provenance()


def test_checksum_matches_the_contract_in_the_repository():
    proto = REPO / "proto" / "memco" / "memory" / "v1" / "memory.proto"
    expected = hashlib.sha256(proto.read_bytes()).hexdigest()
    assert provenance().protos[0].sha256 == expected


def test_parse_reads_the_generated_shape():
    p = parse(
        """
# Generated by the server repository's SDK export. Do not edit.
server_commit: abc123
codegen:
  python:
    grpcio_tools: unknown
requires:
  python:
    grpcio: ">=1.76.0,<2"
protos:
  - path: memco/memory/v1/memory.proto
    sha256: deadbeef
"""
    )
    assert p.server_commit == "abc123"
    assert len(p.protos) == 1
    assert (p.protos[0].path, p.protos[0].sha256) == ("memco/memory/v1/memory.proto", "deadbeef")


def test_nested_keys_cannot_impersonate_the_real_ones():
    # The descriptor nests other languages' sections, several of which use the
    # same key names. Only the top-level commit and the protos list may count.
    p = parse(
        """
codegen:
  nested:
    server_commit: DECOY
    path: decoy.proto
    sha256: decoysha
protos:
  - path: real.proto
    sha256: realsha
server_commit: REAL
"""
    )
    assert p.server_commit == "REAL"
    assert [(r.path, r.sha256) for r in p.protos] == [("real.proto", "realsha")]


@pytest.mark.parametrize(
    "text",
    [
        "codegen:\n  python: {}\n",  # no server_commit
        "server_commit: abc\n",  # no protos
        "server_commit: abc\nprotos:\n  - path: only-a-path\n",  # proto without a checksum
    ],
)
def test_malformed_descriptor_raises_rather_than_guessing(text):
    with pytest.raises(ClientConfigError):
        parse(text)


# --- inputs the parser used to accept while returning the wrong answer ----


def test_a_key_merely_ending_in_path_is_not_a_path():
    with pytest.raises(ClientConfigError):
        parse("server_commit: c\nprotos:\n  - filepath: /etc/passwd\n    sha256: deadbeef\n")


def test_a_key_merely_ending_in_sha256_is_not_a_checksum():
    with pytest.raises(ClientConfigError):
        parse("server_commit: c\nprotos:\n  - path: a.proto\n    xsha256: FORGED\n")


def test_a_nested_block_cannot_override_an_entrys_checksum():
    p = parse(
        "server_commit: c\n"
        "protos:\n"
        "  - path: a.proto\n"
        "    sha256: REAL\n"
        "    signature:\n"
        "      sha256: FORGED\n"
    )
    assert p.protos[0].sha256 == "REAL"


def test_a_key_named_inside_another_value_is_not_a_key():
    p = parse(
        "server_commit: c\n"
        "protos:\n"
        "  - path: real.proto\n"
        "    sha256: aaa\n"
        "    note: see path: fake.proto\n"
    )
    assert p.protos[0].path == "real.proto"


def test_a_nested_list_does_not_become_extra_records():
    p = parse(
        "server_commit: c\n"
        "protos:\n"
        "  - path: a\n"
        "    sha256: b\n"
        "    deps:\n"
        "      - path: c\n"
        "        sha256: d\n"
    )
    assert [(r.path, r.sha256) for r in p.protos] == [("a", "b")]


def test_a_comment_at_column_zero_does_not_truncate_the_list():
    p = parse(
        "server_commit: c\n"
        "protos:\n"
        "  - path: a\n"
        "    sha256: b\n"
        "# a note\n"
        "  - path: c\n"
        "    sha256: d\n"
    )
    assert [r.path for r in p.protos] == ["a", "c"]


def test_a_hash_inside_quotes_is_not_a_comment():
    p = parse('server_commit: "abc#123"\nprotos:\n  - path: a\n    sha256: b\n')
    assert p.server_commit == "abc#123"


def test_a_block_scalar_is_rejected_rather_than_misread():
    with pytest.raises(ClientConfigError, match="block scalar"):
        parse("server_commit: |\n  abc\nprotos:\n  - path: a\n    sha256: b\n")


def test_a_duplicated_field_in_one_entry_is_rejected():
    with pytest.raises(ClientConfigError, match="twice"):
        parse("server_commit: c\nprotos:\n  - path: a\n    sha256: b\n    sha256: c\n")


def test_crlf_line_endings_parse():
    p = parse("server_commit: c\r\nprotos:\r\n  - path: a\r\n    sha256: b\r\n")
    assert (p.server_commit, p.protos[0].path) == ("c", "a")


def test_the_packaged_licence_matches_the_repository_root():
    # The wheel needs its own copy — a path outside the project root produces a
    # malformed archive entry — so this guards the two against drifting apart.
    packaged = REPO / "python" / "LICENSE"
    root = REPO / "LICENSE"
    assert packaged.read_text() == root.read_text(), (
        "python/LICENSE has drifted from the repository LICENSE; copy it across"
    )
