package provenance

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
	"testing"

	"github.com/memcoai/memcoai/go/internal/fault"
)

func TestTheEmbeddedDescriptorNamesTheContract(t *testing.T) {
	record, err := Read()
	if err != nil {
		t.Fatal(err)
	}
	if !regexp.MustCompile(`^[0-9a-f]{40}$`).MatchString(record.ServerCommit) {
		t.Errorf("server commit %q", record.ServerCommit)
	}
	// Every contract in the repository, in the lexical order the export writes
	// them, so a contract the descriptor drops or a stale checksum both show.
	const root = "../../../proto"
	var want []Proto
	err = filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() || filepath.Ext(path) != ".proto" {
			return err
		}
		contract, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		sum := sha256.Sum256(contract)
		want = append(want, Proto{Path: filepath.ToSlash(rel), SHA256: hex.EncodeToString(sum[:])})
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(record.Protos, want) {
		t.Errorf("protos %+v, want %+v", record.Protos, want)
	}
}

func TestReadHandsOutCopies(t *testing.T) {
	first, err := Read()
	if err != nil {
		t.Fatal(err)
	}
	first.Protos[0].Path = "changed"
	second, _ := Read()
	if second.Protos[0].Path == "changed" {
		t.Fatal("a caller's edit reached the cached descriptor")
	}
}

func parsed(t *testing.T, text string) Record {
	t.Helper()
	record, err := Parse(text)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	return record
}

func refused(t *testing.T, text, want string) {
	t.Helper()
	_, err := Parse(text)
	var f *fault.Error
	if !errors.As(err, &f) || f.Kind != fault.KindConfig {
		t.Fatalf("got %v, want a config error", err)
	}
	if !strings.Contains(f.Detail, want) {
		t.Fatalf("got %q, want it to contain %q", f.Detail, want)
	}
}

func TestTheGeneratedShapeParses(t *testing.T) {
	record := parsed(t, `
# Generated by the server repository's SDK export. Do not edit.
server_commit: abc123
codegen:
  python:
    grpcio_tools: unknown
requires:
  python:
    grpcio: ">=1.76.0,<2"
protos:
  - path: memcoai/memory/v1/memory.proto
    sha256: deadbeef
`)
	want := Record{ServerCommit: "abc123", Protos: []Proto{{"memcoai/memory/v1/memory.proto", "deadbeef"}}}
	if !reflect.DeepEqual(record, want) {
		t.Fatalf("got %+v", record)
	}
}

func TestNestedKeysCannotImpersonateTheRealOnes(t *testing.T) {
	record := parsed(t, `
codegen:
  nested:
    server_commit: DECOY
    path: decoy.proto
    sha256: decoysha
protos:
  - path: real.proto
    sha256: realsha
server_commit: REAL
`)
	if record.ServerCommit != "REAL" || !reflect.DeepEqual(record.Protos, []Proto{{"real.proto", "realsha"}}) {
		t.Fatalf("got %+v", record)
	}
}

func TestAMalformedDescriptorIsRefused(t *testing.T) {
	refused(t, "codegen:\n  python: {}\n", "SDK_PROVENANCE.yaml is missing server_commit")
	refused(t, "protos:\n  - path: a\n    sha256: b\n", "SDK_PROVENANCE.yaml is missing server_commit")
	refused(t, "server_commit: abc\n", "SDK_PROVENANCE.yaml lists no protos")
	refused(t, "server_commit: abc\nprotos:\n  - path: only-a-path\n",
		`SDK_PROVENANCE.yaml has a protos entry missing path or sha256: {"path":"only-a-path"}`)
	refused(t, "server_commit: c\nprotos:\n  -\n", "SDK_PROVENANCE.yaml has an empty protos entry")
	refused(t, "server_commit: c\nprotos:\n  - filepath: /etc/passwd\n    sha256: deadbeef\n", "missing path or sha256")
	refused(t, "server_commit: c\nprotos:\n  - path: a.proto\n    xsha256: FORGED\n", "missing path or sha256")
	refused(t, "server_commit: |\n  abc\nprotos:\n  - path: a\n    sha256: b\n",
		"SDK_PROVENANCE.yaml uses an unsupported block scalar for server_commit")
	refused(t, "server_commit: c\nprotos:\n  - path: a\n    sha256: b\n    sha256: c\n",
		"SDK_PROVENANCE.yaml has a protos entry naming sha256 twice")
}

func TestANestedBlockCannotOverrideAChecksum(t *testing.T) {
	record := parsed(t, "server_commit: c\nprotos:\n  - path: a.proto\n    sha256: REAL\n    signature:\n      sha256: FORGED\n")
	if record.Protos[0].SHA256 != "REAL" {
		t.Fatalf("got %+v", record)
	}
}

func TestAKeyNamedInsideAnotherValueIsNotAKey(t *testing.T) {
	record := parsed(t, "server_commit: c\nprotos:\n  - path: real.proto\n    sha256: aaa\n    note: see path: fake.proto\n")
	if record.Protos[0].Path != "real.proto" {
		t.Fatalf("got %+v", record)
	}
}

func TestANestedListDoesNotBecomeExtraRecords(t *testing.T) {
	record := parsed(t, "server_commit: c\nprotos:\n  - path: a\n    sha256: b\n    deps:\n      - path: c\n        sha256: d\n")
	if !reflect.DeepEqual(record.Protos, []Proto{{"a", "b"}}) {
		t.Fatalf("got %+v", record)
	}
}

func TestACommentAtColumnZeroDoesNotTruncateTheList(t *testing.T) {
	record := parsed(t, "server_commit: c\nprotos:\n  - path: a\n    sha256: b\n# a note\n  - path: c\n    sha256: d\n")
	if !reflect.DeepEqual(record.Protos, []Proto{{"a", "b"}, {"c", "d"}}) {
		t.Fatalf("got %+v", record)
	}
}

func TestAHashInsideQuotesIsNotAComment(t *testing.T) {
	record := parsed(t, "server_commit: \"abc#123\"\nprotos:\n  - path: a\n    sha256: b\n")
	if record.ServerCommit != "abc#123" {
		t.Fatalf("got %+v", record)
	}
	record = parsed(t, "server_commit: 'abc' # trailing\nprotos:\n  - path: a\n    sha256: b\n")
	if record.ServerCommit != "abc" {
		t.Fatalf("got %+v", record)
	}
}

func TestCRLFLineEndingsParse(t *testing.T) {
	record := parsed(t, "server_commit: c\r\nprotos:\r\n  - path: a\r\n    sha256: b\r\n")
	if record.ServerCommit != "c" || record.Protos[0].Path != "a" {
		t.Fatalf("got %+v", record)
	}
}

func TestEverySequenceStyleParses(t *testing.T) {
	styles := map[string]string{
		"dash alone": "server_commit: c\nprotos:\n  -\n    path: a.proto\n    sha256: b\n",
		"inline":     "server_commit: c\nprotos:\n  - path: a.proto\n    sha256: b\n",
		"flush left": "server_commit: c\nprotos:\n- path: a.proto\n  sha256: b\n",
		"wide dash":  "server_commit: c\nprotos:\n  -   path: a.proto\n      sha256: b\n",
	}
	for style, text := range styles {
		if record := parsed(t, text); !reflect.DeepEqual(record.Protos, []Proto{{"a.proto", "b"}}) {
			t.Errorf("%s: got %+v", style, record)
		}
	}
}

func TestSeveralDashAloneEntriesStaySeparate(t *testing.T) {
	record := parsed(t, "server_commit: c\nprotos:\n  -\n    path: a\n    sha256: b\n  -\n    path: c\n    sha256: d\n")
	if !reflect.DeepEqual(record.Protos, []Proto{{"a", "b"}, {"c", "d"}}) {
		t.Fatalf("got %+v", record)
	}
}
