"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from memcoai.auth.v1 import auth_pb2 as _auth_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class TokenServiceStub:
    """TokenService turns an API client's credentials into a bearer token.

    It is the one service called without a token of its own — the credentials in
    the request are what authenticate it — so it lives apart from the services that
    require one, and a client can bootstrap over gRPC with no HTTP client at all.
    The same exchange is served over REST at /api/external/v1/oauth/token.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TokenServiceAsyncStub: ...
    IssueToken: _grpc.UnaryUnaryMultiCallable[_auth_pb2.IssueTokenRequest, _auth_pb2.IssueTokenResponse]
    """IssueToken performs the OAuth 2.0 client-credentials grant (RFC 6749 §4.4).

    The token is a bearer credential for the operations the client was created
    for, and expires on its own. Every credential failure — an unknown client, a
    wrong secret, a retired one — is the same UNAUTHENTICATED answer, so nothing
    about which part was wrong is disclosed.
    """

@_typing.type_check_only
class TokenServiceAsyncStub(TokenServiceStub):
    """TokenService turns an API client's credentials into a bearer token.

    It is the one service called without a token of its own — the credentials in
    the request are what authenticate it — so it lives apart from the services that
    require one, and a client can bootstrap over gRPC with no HTTP client at all.
    The same exchange is served over REST at /api/external/v1/oauth/token.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    IssueToken: _aio.UnaryUnaryMultiCallable[_auth_pb2.IssueTokenRequest, _auth_pb2.IssueTokenResponse]  # type: ignore[assignment]
    """IssueToken performs the OAuth 2.0 client-credentials grant (RFC 6749 §4.4).

    The token is a bearer credential for the operations the client was created
    for, and expires on its own. Every credential failure — an unknown client, a
    wrong secret, a retired one — is the same UNAUTHENTICATED answer, so nothing
    about which part was wrong is disclosed.
    """

class TokenServiceServicer(metaclass=_abc_1.ABCMeta):
    """TokenService turns an API client's credentials into a bearer token.

    It is the one service called without a token of its own — the credentials in
    the request are what authenticate it — so it lives apart from the services that
    require one, and a client can bootstrap over gRPC with no HTTP client at all.
    The same exchange is served over REST at /api/external/v1/oauth/token.
    """

    @_abc_1.abstractmethod
    def IssueToken(
        self,
        request: _auth_pb2.IssueTokenRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_auth_pb2.IssueTokenResponse, _abc.Awaitable[_auth_pb2.IssueTokenResponse]]:
        """IssueToken performs the OAuth 2.0 client-credentials grant (RFC 6749 §4.4).

        The token is a bearer credential for the operations the client was created
        for, and expires on its own. Every credential failure — an unknown client, a
        wrong secret, a retired one — is the same UNAUTHENTICATED answer, so nothing
        about which part was wrong is disclosed.
        """

def add_TokenServiceServicer_to_server(servicer: TokenServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
